/**
 * CKF Phase 3c — Final batch: Vauxhall Insignia/Zafira · Skoda Fabia · Mini Countryman
 *                              Toyota Corolla · Fiat Punto · Land Rover Evoque/Discovery Sport
 */
import { createClient } from "@supabase/supabase-js";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const ws = require("ws");

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
  { auth: { persistSession: false }, realtime: { transport: ws } }
);

const up  = async (t, r, c) => { const { data, error } = await sb.from(t).upsert(r, { onConflict: c }).select(); if (error) throw new Error(`[${t}] ${error.message}`); return data; };
const ins = async (t, r, c) => { const { error } = await sb.from(t).upsert(r, { onConflict: c, ignoreDuplicates: true }); if (error) throw new Error(`[${t}] ${error.message}`); };
const get = (arr, slug) => { const r = arr.find(x => x.slug === slug); if (!r) throw new Error(`Missing: ${slug}`); return r; };

async function run() {
  console.log("Phase 3c — Vauxhall · Skoda · Mini · Toyota · Fiat · Land Rover\n");

  const { data: models } = await sb.from("models").select("id, slug");
  const { data: tags }   = await sb.from("tags").select("id, slug");

  const variantRows = [
    { model_id: get(models,"insignia").id,        name: "Mk1 2.0 CDTi 130bhp",        slug: "insignia-mk1-20-cdti",     engine: "2.0 CDTi 130bhp",   year_start: 2008, year_end: 2017, body_type: "Saloon",    transmission: "Manual",    fuel_type: "Diesel",  description: "Vauxhall's executive diesel. High fleet mileages reveal DPF, EGR and timing chain weaknesses." },
    { model_id: get(models,"zafira").id,           name: "Mk2 1.9 CDTi 120bhp",        slug: "zafira-mk2-19-cdti",      engine: "1.9 CDTi 120bhp",   year_start: 2005, year_end: 2014, body_type: "MPV",       transmission: "Manual",    fuel_type: "Diesel",  description: "Family MPV diesel. DPF blockage from school-run use and turbo issues are the key concerns." },
    { model_id: get(models,"fabia").id,            name: "Mk2 1.4 TDI 80bhp",          slug: "fabia-mk2-14-tdi",        engine: "1.4 TDI 80bhp PD",  year_start: 2007, year_end: 2014, body_type: "Hatchback", transmission: "Manual",    fuel_type: "Diesel",  description: "Compact diesel Fabia. Timing belt and DPF are the critical maintenance items." },
    { model_id: get(models,"countryman").id,       name: "R60 Cooper D 2.0d 112bhp",   slug: "r60-cooper-d-20d",        engine: "2.0d 112bhp N47",   year_start: 2010, year_end: 2016, body_type: "SUV",       transmission: "Manual",    fuel_type: "Diesel",  description: "Mini's SUV uses the BMW N47 engine — the same rear-mounted timing chain problem as the 3 Series." },
    { model_id: get(models,"corolla").id,          name: "Mk9 1.4 D-4D 90bhp",         slug: "corolla-mk9-14-d4d",      engine: "1.4 D-4D 90bhp",    year_start: 2004, year_end: 2007, body_type: "Hatchback", transmission: "Manual",    fuel_type: "Diesel",  description: "Toyota's diesel Corolla. Generally reliable but DPF and injector issues affect higher-mileage examples." },
    { model_id: get(models,"corolla").id,          name: "Mk10 1.6 VVT-i 132bhp",      slug: "corolla-mk10-16-vvti",    engine: "1.6 VVT-i 132bhp",  year_start: 2007, year_end: 2013, body_type: "Hatchback", transmission: "Manual",    fuel_type: "Petrol",  description: "Reliable petrol Corolla. Steering rack and oil burning issues are the main concerns." },
    { model_id: get(models,"punto").id,            name: "Mk3 1.3 Multijet 75bhp",     slug: "punto-mk3-13-multijet",   engine: "1.3 Multijet 75bhp",year_start: 2005, year_end: 2018, body_type: "Hatchback", transmission: "Manual",    fuel_type: "Diesel",  description: "The Punto's longest-lived engine. EGR failure and clutch actuator issues are the most common faults." },
    { model_id: get(models,"range-rover-evoque").id, name: "Mk1 2.2 TD4 150bhp",       slug: "evoque-mk1-22-td4",       engine: "2.2 TD4 150bhp",    year_start: 2011, year_end: 2018, body_type: "SUV",       transmission: "Automatic", fuel_type: "Diesel",  description: "Land Rover's premium compact SUV. Timing belt, EGR and gearbox issues are the primary concerns." },
    { model_id: get(models,"discovery-sport").id,  name: "Mk1 2.0 TD4 150bhp",         slug: "disco-sport-mk1-20-td4",  engine: "2.0 TD4 150bhp",    year_start: 2014, year_end: 2019, body_type: "SUV",       transmission: "Automatic", fuel_type: "Diesel",  description: "Land Rover's Freelander replacement. Ingium engine faults, EGR issues and gearbox concerns are emerging on higher-mileage examples." },
  ];

  const variants = await up("variants", variantRows, "model_id,slug");
  console.log(`Variants: ${variants.length}`);
  const vid = s => get(variants, s).id;

  const faultRows = [
    // ── Vauxhall Insignia 2.0 CDTi ───────────────────────────────────────
    { variant_id: vid("insignia-mk1-20-cdti"), title: "Timing Chain Failure", slug: "insignia-cdti-timing-chain", summary: "The A20DTH/DTJ 2.0 CDTi Insignia shares the timing chain weakness of the Astra J 1.6 CDTi. Chain rattle on cold start is the warning sign — ignore it at your peril.", symptoms: "- Cold-start chain rattle from top of engine\n- EML with P0016/P0017\n- Rough cold running\n- Metallic rattle under acceleration", cause: "The timing chain tensioner weakens with mileage. Infrequent oil changes accelerate chain stretch and guide wear.", fix: "1. Do not drive with persistent chain rattle\n2. Full timing chain kit replacement\n3. Cost: £900-1,600 fitted at indie specialist", severity: "critical", mileage_start: 70000, mileage_end: 140000, repair_cost_low: 900, repair_cost_high: 1600, diy_difficulty: "professional_only", affected_years: "2008-2017", obd_codes: ["P0016","P0017"], published: true },
    { variant_id: vid("insignia-mk1-20-cdti"), title: "DPF Blockage", slug: "insignia-cdti-dpf", summary: "The Insignia 2.0 CDTi is a fleet rep car often driven on short local trips rather than the motorway runs it is designed for. DPF blockage is endemic on urban-use examples.", symptoms: "- DPF warning light\n- Power loss\n- Oil level rising\n- P2452/P2453 codes", cause: "Short trips at low speed prevent DPF regeneration. Failed regens contaminate engine oil with diesel fuel.", fix: "1. Check oil for diesel dilution first\n2. Force regen via Tech2 or compatible tool\n3. Professional DPF clean: £250-400\n4. Replacement: £700-1,300", severity: "moderate", mileage_start: 50000, mileage_end: 100000, repair_cost_low: 250, repair_cost_high: 1300, diy_difficulty: "moderate", affected_years: "2008-2017", obd_codes: ["P2452","P2453"], published: true },
    { variant_id: vid("insignia-mk1-20-cdti"), title: "EGR Cooler Failure", slug: "insignia-cdti-egr-cooler", summary: "EGR cooler failure on the Insignia 2.0 CDTi causes coolant to enter the intake manifold — a serious failure that requires immediate attention.", symptoms: "- Coolant level dropping\n- White smoke with sweet smell\n- Rough running\n- P0401 EGR code", cause: "EGR cooler internal corrosion allows coolant to leak into the intake path. Combined with EGR valve carbonising, both typically need addressing together.", fix: "1. Replace EGR cooler and valve together\n2. Flush intake manifold\n3. Cost: £600-1,000 fitted", severity: "severe", mileage_start: 70000, mileage_end: 140000, repair_cost_low: 600, repair_cost_high: 1000, diy_difficulty: "hard", affected_years: "2008-2017", obd_codes: ["P0401","P0128"], published: true },
    { variant_id: vid("insignia-mk1-20-cdti"), title: "Turbocharger Failure", slug: "insignia-cdti-turbo", summary: "Turbo failure on the Insignia 2.0 CDTi follows the standard pattern — oil sludge in the feed pipe starves the bearings, often on cars with extended oil change intervals.", symptoms: "- Whining from turbo\n- Loss of power\n- Blue smoke\n- P0299 underboost", cause: "Sludged oil feed pipe from infrequent changes. The Insignia's higher mass increases turbo load at low speed.", fix: "1. Check oil feed pipe\n2. Remanufactured turbo: £450-750\n3. Flush oil on installation\n4. Fitted: £700-1,200", severity: "severe", mileage_start: 100000, mileage_end: 180000, repair_cost_low: 700, repair_cost_high: 1200, diy_difficulty: "hard", affected_years: "2008-2017", obd_codes: ["P0299"], published: true },
    { variant_id: vid("insignia-mk1-20-cdti"), title: "Injector Failure", slug: "insignia-cdti-injectors", summary: "High-mileage Insignia CDTi examples develop injector wear, causing rough running and rising oil levels from diesel contamination.", symptoms: "- Rough idle\n- Hard starting\n- White smoke\n- Rising oil level\n- P0201-P0204 codes", cause: "Common rail injector wear at high mileage. Contaminated fuel or overextended service intervals accelerate degradation.", fix: "1. Contribution test — identifies failing cylinder\n2. Ultrasonic clean before replacement\n3. New injectors coded to ECU\n4. Cost: £300-600 per injector fitted", severity: "severe", mileage_start: 110000, mileage_end: 200000, repair_cost_low: 350, repair_cost_high: 1200, diy_difficulty: "professional_only", affected_years: "2008-2017", obd_codes: ["P0201","P0202"], published: true },

    // ── Vauxhall Zafira Mk2 1.9 CDTi ─────────────────────────────────────
    { variant_id: vid("zafira-mk2-19-cdti"), title: "DPF Blockage from Family Use", slug: "zafira-cdti-dpf", summary: "The Zafira Mk2 1.9 CDTi is the classic family MPV diesel — used for exactly the kind of school runs and local trips that block DPFs. It is the most commonly reported Zafira fault.", symptoms: "- DPF warning light\n- Power loss\n- Oil above max (diesel dilution)\n- P2452/P2453 codes", cause: "Family MPV use means short, cold, low-speed journeys. The diesel engine and DPF simply cannot self-clean under these conditions.", fix: "1. Check oil for diesel dilution immediately\n2. Force regen via Tech2 or compatible OBD tool\n3. Professional DPF clean: £200-350\n4. Seriously consider petrol Zafira for family use", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 200, repair_cost_high: 900, diy_difficulty: "moderate", affected_years: "2005-2014", obd_codes: ["P2452","P2453"], published: true },
    { variant_id: vid("zafira-mk2-19-cdti"), title: "Turbocharger Variable Vane Failure", slug: "zafira-cdti-turbo", summary: "The variable-vane turbocharger on the 1.9 CDTi Zafira develops sticky vanes from carbon build-up, causing limp mode and poor performance.", symptoms: "- Loss of power above 2,000 RPM\n- Limp mode\n- P0299 underboost or P0234 overboost\n- Smoke under hard acceleration", cause: "Variable vanes accumulate carbon from low-speed urban use. The vanes stick, preventing the turbo from generating correct boost pressure.", fix: "1. Remove turbo and clean vanes — often restores function\n2. Replacement if vanes corroded: £450-750 remanufactured\n3. Flush oil system on installation\n4. Fitted: £650-1,050", severity: "severe", mileage_start: 70000, mileage_end: 140000, repair_cost_low: 200, repair_cost_high: 1050, diy_difficulty: "hard", affected_years: "2005-2014", obd_codes: ["P0299","P0234"], published: true },
    { variant_id: vid("zafira-mk2-19-cdti"), title: "EGR Valve Carbon Blockage", slug: "zafira-cdti-egr", summary: "EGR failure on the Zafira 1.9 CDTi is common in MPV use. The valve carbons up rapidly with the stop-start urban driving profile typical of family vehicles.", symptoms: "- EML and power loss\n- Rough idle\n- Black smoke\n- P0400/P0401 codes", cause: "Carbon deposits accumulate on the EGR valve and restrict exhaust gas recirculation flow. Urban family use creates ideal conditions for rapid fouling.", fix: "1. Remove and clean EGR valve\n2. Clean intake manifold passages\n3. Replacement EGR: £100-250\n4. Full job: £200-400", severity: "moderate", mileage_start: 50000, mileage_end: 100000, repair_cost_low: 100, repair_cost_high: 400, diy_difficulty: "moderate", affected_years: "2005-2014", obd_codes: ["P0400","P0401"], published: true },
    { variant_id: vid("zafira-mk2-19-cdti"), title: "Dual Mass Flywheel Failure", slug: "zafira-cdti-dmf", summary: "DMF wear on the Zafira 1.9 CDTi is a routine high-mileage repair. The combination of diesel torque and the MPV's weight accelerates flywheel wear.", symptoms: "- Juddering clutch engagement\n- Rattle at idle from bellhousing\n- Vibration through gear lever\n- Clunking gear changes", cause: "The DMF spring dampers lose effectiveness with mileage. MPV use with frequent loaded start-stop driving accelerates wear.", fix: "1. Replace DMF and clutch together\n2. LuK or Sachs kits recommended\n3. Solid flywheel conversion is cost-effective long-term\n4. Labour: 5 hours. Total: £700-1,100", severity: "moderate", mileage_start: 90000, mileage_end: 170000, repair_cost_low: 700, repair_cost_high: 1100, diy_difficulty: "professional_only", affected_years: "2005-2014", obd_codes: [], published: true },

    // ── Skoda Fabia Mk2 1.4 TDI ──────────────────────────────────────────
    { variant_id: vid("fabia-mk2-14-tdi"), title: "Timing Belt Failure", slug: "fabia-mk2-tdi-timing-belt", summary: "The 1.4 TDI Fabia has a timing belt with a 60,000-mile or 4-year interval. Belt failure on this interference engine is catastrophic — bent valves and destroyed pistons are the result.", symptoms: "- No warning before failure\n- Engine stops suddenly while driving\n- Will not restart after failure\n- Catastrophic internal engine damage", cause: "Rubber timing belt degradation with age and heat. The strict VAG 60k/4yr interval is non-negotiable. Many used Fabias have unknown belt history.", fix: "1. Replace belt, tensioner, idler and water pump as a kit\n2. If history unknown: replace immediately\n3. Gates or Dayco kit only — no pattern parts on a timing belt\n4. Cost: £280-500 fitted", severity: "critical", mileage_start: 1, mileage_end: 60000, repair_cost_low: 280, repair_cost_high: 500, diy_difficulty: "hard", affected_years: "2007-2014", obd_codes: [], published: true },
    { variant_id: vid("fabia-mk2-14-tdi"), title: "DPF Blockage", slug: "fabia-mk2-tdi-dpf", summary: "The small 1.4 TDI Fabia is often used for city commuting — the exact use case that blocks DPFs. The engine's small displacement means low exhaust temperatures even at motorway speeds.", symptoms: "- DPF warning light\n- Power loss\n- P2452/P2453 codes\n- Black smoke", cause: "The 1.4-litre engine cannot generate sufficient exhaust temperatures for DPF regeneration in urban driving. City-only use is incompatible with this engine.", fix: "1. 30-min motorway run at sustained RPM\n2. Force regen via VCDS\n3. Professional DPF clean: £150-300\n4. Consider petrol Fabia for city use", severity: "moderate", mileage_start: 30000, mileage_end: 70000, repair_cost_low: 150, repair_cost_high: 800, diy_difficulty: "moderate", affected_years: "2007-2014", obd_codes: ["P2452","P2453"], published: true },
    { variant_id: vid("fabia-mk2-14-tdi"), title: "EGR Valve Failure", slug: "fabia-mk2-tdi-egr", summary: "EGR valve carbon build-up on the 1.4 TDI Fabia restricts airflow and causes power loss. The small engine is particularly sensitive to EGR restriction.", symptoms: "- EML and power loss\n- Rough idle\n- Black smoke\n- P0400/P0401 codes", cause: "Carbon deposits on the EGR valve restrict exhaust gas recirculation. Urban use and short trips accelerate fouling.", fix: "1. Remove and clean EGR valve — straightforward on this engine\n2. Clean intake manifold\n3. Replacement if seized: £80-200\n4. Total: £150-350", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 80, repair_cost_high: 350, diy_difficulty: "moderate", affected_years: "2007-2014", obd_codes: ["P0400","P0401"], published: true },
    { variant_id: vid("fabia-mk2-14-tdi"), title: "Glow Plug Failure", slug: "fabia-mk2-tdi-glow-plug", summary: "Glow plug failure on the 1.4 TDI Fabia causes white smoke and hard cold starting. The engine's small combustion chamber is particularly reliant on glow plugs in cold UK winters.", symptoms: "- White smoke on cold start\n- Long cranking before starting\n- Rough running when cold\n- Glow plug warning light\n- P0671-P0674 codes", cause: "Glow plugs are consumable items rated for approximately 100,000 miles. They can seize in the head on high-mileage examples, making removal risky.", fix: "1. Test each plug — open circuit = failed\n2. Soak in penetrating fluid before removal\n3. Never force a seized plug\n4. Replace all four — NGK or Bosch recommended\n5. Cost: £100-200", severity: "moderate", mileage_start: 80000, mileage_end: 150000, repair_cost_low: 100, repair_cost_high: 300, diy_difficulty: "moderate", affected_years: "2007-2014", obd_codes: ["P0671","P0672"], published: true },

    // ── Mini Countryman R60 Cooper D ──────────────────────────────────────
    { variant_id: vid("r60-cooper-d-20d"), title: "N47 Rear Timing Chain Failure", slug: "countryman-n47-timing-chain", summary: "The Mini Countryman Cooper D uses BMW's N47 diesel engine — the same unit fitted to the 3 Series with its infamously rear-mounted timing chain. The Countryman shares every aspect of this catastrophic failure mode.", symptoms: "- Rattling from rear of engine on cold start\n- Noise fades when warm but returns on cold mornings\n- P0016/P0017 timing codes\n- In failure: sudden engine stop, catastrophic damage", cause: "BMW placed the N47 timing chain at the rear of the engine. The chain, guides and tensioner all wear — and engine removal is required for repair, making it extremely expensive.", fix: "1. Listen for rattle from behind the engine — this is not normal\n2. Stop driving immediately if heard\n3. Engine removal required for chain kit replacement\n4. Cost: £2,500-4,000 at a BMW/Mini specialist\n5. Always ask about timing chain history before buying any N47 Countryman", severity: "critical", mileage_start: 80000, mileage_end: 160000, repair_cost_low: 2500, repair_cost_high: 4000, diy_difficulty: "professional_only", affected_years: "2010-2016", obd_codes: ["P0016","P0017"], published: true },
    { variant_id: vid("r60-cooper-d-20d"), title: "Haldex 4WD System Failure", slug: "countryman-haldex-failure", summary: "4WD Countryman models use a Haldex rear differential that requires regular oil and filter changes. Neglected units lose rear drive capability.", symptoms: "- Poor traction in slippery conditions\n- 4WD fault light on dashboard\n- Rear wheels not receiving drive", cause: "The Haldex clutch pack and pump wear when fluid is not changed at 40,000-mile intervals. Many owners are unaware of this service requirement.", fix: "1. Haldex fluid and filter service: £100-200 (do this on purchase if history unknown)\n2. Pump replacement if worn: £400-700\n3. Full unit: £1,000-2,000", severity: "moderate", mileage_start: 60000, mileage_end: 150000, repair_cost_low: 100, repair_cost_high: 2000, diy_difficulty: "moderate", affected_years: "2010-2016", obd_codes: [], published: true },
    { variant_id: vid("r60-cooper-d-20d"), title: "DPF Blockage", slug: "countryman-dpf-blockage", summary: "The Countryman diesel is used as a family urban SUV — frequently on short trips that prevent DPF regeneration. Blockage is the most commonly reported fault.", symptoms: "- DPF warning light\n- Power loss\n- Oil level rising (diesel dilution)\n- P2452/P2453 codes", cause: "Short urban trips in the Countryman prevent DPF regeneration. The N47's exhaust temperatures are insufficient in traffic for passive regen.", fix: "1. Check oil for diesel dilution first\n2. Force regen via diagnostic tool\n3. Professional DPF clean: £250-400\n4. Replacement: £700-1,400", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 250, repair_cost_high: 1400, diy_difficulty: "moderate", affected_years: "2010-2016", obd_codes: ["P2452","P2453"], published: true },
    { variant_id: vid("r60-cooper-d-20d"), title: "EGR Valve and Swirl Flap Failure", slug: "countryman-egr-swirl", summary: "The N47-powered Countryman shares the EGR and swirl flap failure modes of the 3 Series. Both are serious issues that should be addressed preventatively.", symptoms: "- EML with power restriction (EGR)\n- Sudden power loss with bang (swirl flap ingestion)\n- P0401 (EGR) or P2004/P2008 (swirl flap) codes", cause: "EGR valve carbons up with urban use; swirl flap actuator rods corrode and snap, allowing the flap to be ingested into the engine.", fix: "1. Preventative: remove swirl flaps and fit blanking plates (£30-50, 2-3 hours)\n2. EGR clean or replacement at high mileage\n3. Post-swirl-flap failure: compression test all cylinders\n4. Engine rebuild if piston damage: £3,000+", severity: "critical", mileage_start: 60000, mileage_end: 130000, repair_cost_low: 30, repair_cost_high: 4000, diy_difficulty: "moderate", affected_years: "2010-2016", obd_codes: ["P0401","P2004","P2008"], published: true },

    // ── Toyota Corolla Mk9 1.4 D-4D ───────────────────────────────────────
    { variant_id: vid("corolla-mk9-14-d4d"), title: "DPF Blockage and Injector Fouling", slug: "corolla-mk9-dpf-injectors", summary: "The Corolla Mk9 diesel is generally reliable, but DPF blockage affects city-driven examples and injector fouling occurs at high mileage. Toyota quality means these are manageable issues.", symptoms: "- DPF warning light (later models)\n- Rough idle and smoke (injectors)\n- Hard starting when cold\n- P2452/P2453 or P0201-P0204 codes", cause: "Short trips prevent DPF regeneration. Injector wear on high-mileage examples causes rough running.", fix: "1. Force regen via Toyota Techstream or compatible OBD tool\n2. Professional DPF clean: £150-300\n3. Injector clean and test before replacement\n4. Toyota diesel reliability means these faults are usually resolved cost-effectively", severity: "moderate", mileage_start: 60000, mileage_end: 130000, repair_cost_low: 150, repair_cost_high: 700, diy_difficulty: "moderate", affected_years: "2004-2007", obd_codes: ["P2452","P0201"], published: true },
    { variant_id: vid("corolla-mk9-14-d4d"), title: "EGR Valve Failure", slug: "corolla-mk9-egr", summary: "EGR failure on the Corolla Mk9 diesel causes power loss and rough running. While Toyota quality means the EGR lasts longer than European equivalents, it is still a wear item.", symptoms: "- EML and power loss\n- Rough idle\n- Increased fuel consumption\n- P0401 codes", cause: "Carbon deposits accumulate on the EGR valve. Toyota's engineering means the valve is more durable than PSA or VAG equivalents, but it still wears at high mileage.", fix: "1. Remove and clean EGR valve\n2. Clean intake manifold\n3. Replacement OEM Toyota part: £150-300\n4. Fitted: £250-450", severity: "moderate", mileage_start: 80000, mileage_end: 150000, repair_cost_low: 150, repair_cost_high: 450, diy_difficulty: "moderate", affected_years: "2004-2007", obd_codes: ["P0401"], published: true },

    // ── Toyota Corolla Mk10 1.6 VVT-i ─────────────────────────────────────
    { variant_id: vid("corolla-mk10-16-vvti"), title: "Oil Burning and Excessive Consumption", slug: "corolla-mk10-oil-consumption", summary: "Some Corolla Mk10 1.6 VVT-i examples develop excessive oil consumption, needing top-up between services. Toyota extended warranty coverage on affected engines.", symptoms: "- Oil level dropping between 6,000-mile service intervals\n- Blue smoke on startup or overrun\n- Need to add oil every 2,000-3,000 miles\n- Fouled spark plugs (oil contamination)", cause: "Piston ring wear on some production batches allows oil to enter the combustion chamber. Toyota revised the piston ring specification on later engines.", fix: "1. Check if build date falls within affected range\n2. Toyota covered many repairs under extended goodwill — worth checking\n3. Use 5W-40 fully synthetic oil to reduce consumption in the short term\n4. Piston ring replacement or engine rebuild: £1,500-3,000", severity: "moderate", mileage_start: 60000, mileage_end: 130000, repair_cost_low: 200, repair_cost_high: 3000, diy_difficulty: "professional_only", affected_years: "2007-2013", obd_codes: [], published: true },
    { variant_id: vid("corolla-mk10-16-vvti"), title: "Power Steering Rack Knock", slug: "corolla-mk10-steering-knock", summary: "The Corolla Mk10 develops a knock or clunk from the power steering rack at low speeds. It is a wear issue rather than a safety failure, but it becomes progressively more pronounced.", symptoms: "- Clunking from steering rack at low speed\n- Noise when steering over bumps\n- Steering feels vague\n- MOT advisory: steering rack play", cause: "The hydraulic power steering rack wears in its housing. Play develops between the rack and pinion, causing knock when steering forces are applied over road irregularities.", fix: "1. Confirm with steering rack movement test — hold wheel stationary over a bump\n2. Tighten rack adjuster screw if accessible (temporary measure)\n3. Remanufactured rack: £150-300 on exchange\n4. Fitted: £300-500", severity: "minor", mileage_start: 70000, mileage_end: 150000, repair_cost_low: 300, repair_cost_high: 500, diy_difficulty: "moderate", affected_years: "2007-2013", obd_codes: [], published: true },

    // ── Fiat Punto Mk3 1.3 Multijet ───────────────────────────────────────
    { variant_id: vid("punto-mk3-13-multijet"), title: "EGR Valve Failure", slug: "punto-multijet-egr", summary: "EGR failure is the most common fault reported on the Punto Mk3 1.3 Multijet. The small diesel's EGR valve blocks with carbon rapidly in urban use.", symptoms: "- EML and power loss\n- Rough idle and hesitation\n- Black smoke\n- P0400/P0401 codes", cause: "The 1.3 Multijet is the same unit as the Vauxhall 1.3 CDTi. Urban use causes rapid EGR carbon accumulation that blocks the valve and intake.", fix: "1. Remove and clean EGR valve\n2. Clean intake manifold\n3. Replacement: £60-180 pattern, £250 OEM\n4. Total: £150-350 fitted", severity: "moderate", mileage_start: 50000, mileage_end: 100000, repair_cost_low: 80, repair_cost_high: 350, diy_difficulty: "moderate", affected_years: "2005-2018", obd_codes: ["P0400","P0401"], published: true },
    { variant_id: vid("punto-mk3-13-multijet"), title: "Clutch Actuator Failure (Dualogic)", slug: "punto-dualogic-clutch-actuator", summary: "Fiat's Dualogic semi-automatic gearbox uses an electric clutch actuator that fails with age. When it does, the car refuses to pull away — an expensive repair relative to the car's value.", symptoms: "- Gear selection fault warning\n- Car won't pull away\n- Grinding or clunking on gear engagement\n- Car stuck in neutral or refusing to select gears", cause: "The electric clutch actuator motor and sensor wear with use. Cold weather and age exacerbate the failure. Like Renault's EDC, the Dualogic is best avoided.", fix: "1. Confirm with diagnostic — Dualogic fault codes confirm actuator failure\n2. New actuator from Fiat: £600-1,200 fitted\n3. Remanufactured units: £300-600\n4. Consider manual gearbox conversion for long-term ownership", severity: "severe", mileage_start: 50000, mileage_end: 120000, repair_cost_low: 300, repair_cost_high: 1200, diy_difficulty: "professional_only", affected_years: "2005-2018", obd_codes: [], published: true },
    { variant_id: vid("punto-mk3-13-multijet"), title: "Timing Belt Failure", slug: "punto-multijet-timing-belt", summary: "The Punto 1.3 Multijet uses a timing belt with a 60,000-mile interval that Fiat owners frequently overlook. Belt failure on this interference engine is catastrophic.", symptoms: "- No warning before failure\n- Sudden engine stop\n- Engine will not restart\n- Catastrophic valve damage on failure", cause: "Rubber belt degradation at 60k/4yr interval. Fiat's short interval is critical — the small engine places high stress on the belt.", fix: "1. Replace belt, tensioner, idler and water pump at 60k/4yr\n2. If history unknown: replace immediately\n3. Fiat/Magneti Marelli or Gates kit only\n4. Cost: £280-500 fitted", severity: "critical", mileage_start: 1, mileage_end: 60000, repair_cost_low: 280, repair_cost_high: 500, diy_difficulty: "hard", affected_years: "2005-2018", obd_codes: [], published: true },
    { variant_id: vid("punto-mk3-13-multijet"), title: "Rear Arch and Sill Corrosion", slug: "punto-mk3-rust", summary: "The Punto Mk3 has a poor reputation for bodywork corrosion in the UK. Rear wheel arch lips and sill box sections corrode, often failing MOT on older examples.", symptoms: "- Bubbling paint at rear arch lips\n- Visible rust on sill seam\n- Soft sill sections when pressed\n- MOT failure for structural corrosion", cause: "Fiat's factory undersealing on the Punto Mk3 is minimal. UK road salt penetrates sill box sections and arch lips, causing extensive internal corrosion that is invisible until it breaks through.", fix: "1. Annual Waxoyl or Dinitrol cavity wax injection\n2. Treat surface rust immediately before it progresses\n3. Structural sill repair: £400-1,200 at a bodywork specialist\n4. Check all four arches and both sills on any used purchase", severity: "moderate", mileage_start: 1, mileage_end: 999999, repair_cost_low: 200, repair_cost_high: 1200, diy_difficulty: "hard", affected_years: "2005-2018", obd_codes: [], published: true },

    // ── Land Rover Range Rover Evoque Mk1 2.2 TD4 ─────────────────────────
    { variant_id: vid("evoque-mk1-22-td4"), title: "Timing Belt Failure", slug: "evoque-td4-timing-belt", summary: "The 2.2 TD4 Evoque uses a timing belt that must be replaced at 120,000 miles or 10 years — but many specialists recommend 80,000 miles given the consequences of failure.", symptoms: "- No warning before failure\n- Engine stops suddenly\n- Engine will not restart\n- Catastrophic valve and piston damage", cause: "The Ford-derived 2.2 TD4 engine uses a rubber timing belt. Belt failure destroys the engine completely — replacement is not optional.", fix: "1. Replace belt, tensioner, idler and water pump as a kit\n2. Recommend at 80,000 miles rather than 120,000\n3. Land Rover specialist only — access is more complex than standard\n4. Cost: £600-1,000 fitted", severity: "critical", mileage_start: 80000, mileage_end: 130000, repair_cost_low: 600, repair_cost_high: 1000, diy_difficulty: "hard", affected_years: "2011-2018", obd_codes: [], published: true },
    { variant_id: vid("evoque-mk1-22-td4"), title: "9-Speed ZF Automatic Gearbox Shudder", slug: "evoque-9spd-gearbox-shudder", summary: "Evoque models with the 9-speed ZF automatic gearbox suffer from shudder and hesitation at low speeds. Software updates helped but did not fully resolve the issue.", symptoms: "- Shudder or vibration pulling away from 0-10 mph\n- Hesitation on gearbox engagement\n- Jerky low-speed driving\n- Hunting between gears", cause: "The 9-speed ZF gearbox was new technology at launch and the calibration for low-speed engagement was not optimised. Multiple software updates were issued.", fix: "1. Check if latest ZF software update has been applied — often free at Land Rover\n2. Gearbox fluid change if not recently done (every 60,000 miles)\n3. Mechatronic unit replacement if fluid change doesn't resolve: £800-1,500\n4. Full gearbox replacement: £3,000-5,000", severity: "moderate", mileage_start: 1, mileage_end: 80000, repair_cost_low: 100, repair_cost_high: 5000, diy_difficulty: "professional_only", affected_years: "2014-2018", obd_codes: [], published: true },
    { variant_id: vid("evoque-mk1-22-td4"), title: "DPF Blockage", slug: "evoque-td4-dpf", summary: "The Evoque TD4 is frequently used as a school-run and urban lifestyle vehicle — exactly the wrong use for a diesel SUV with a DPF. Blockage is common.", symptoms: "- DPF warning light\n- Power loss\n- Oil level rising\n- P2452/P2453 codes", cause: "Urban use prevents DPF regeneration. The Evoque's premium image attracts buyers who use it for exactly the kind of short trips that block DPFs.", fix: "1. Check oil for diesel dilution\n2. Force regen via JLR diagnostic tool\n3. Professional DPF clean: £250-400\n4. Replacement: £800-1,500", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 250, repair_cost_high: 1500, diy_difficulty: "moderate", affected_years: "2011-2018", obd_codes: ["P2452","P2453"], published: true },
    { variant_id: vid("evoque-mk1-22-td4"), title: "Transfer Box Oil Leak and Failure", slug: "evoque-transfer-box-leak", summary: "The Evoque's 4WD transfer box develops oil leaks from the output shaft seals. Neglected leaks lead to transfer box damage — a significant repair cost.", symptoms: "- Oil dripping from under the car (centre or rear)\n- 4WD fault warning light\n- Grinding or whining from transfer box\n- Reduced 4WD capability", cause: "The transfer box output shaft oil seals wear and allow gear oil to leak. The transfer box itself can also develop bearing wear if fluid level drops.", fix: "1. Inspect underside for oil leaks — transfer box is centre of vehicle\n2. Replace output shaft seals if leaking: £200-400\n3. Refill with correct Land Rover specified gear oil\n4. Transfer box rebuild if bearing damaged: £1,000-2,500", severity: "severe", mileage_start: 60000, mileage_end: 130000, repair_cost_low: 200, repair_cost_high: 2500, diy_difficulty: "hard", affected_years: "2011-2018", obd_codes: [], published: true },

    // ── Land Rover Discovery Sport Mk1 2.0 TD4 ────────────────────────────
    { variant_id: vid("disco-sport-mk1-20-td4"), title: "EGR Valve and Cooler Failure", slug: "disco-sport-egr-failure", summary: "The Ingenium 2.0 TD4 engine in the Discovery Sport develops EGR valve and cooler failures. The cooler can cause coolant to enter the intake on higher-mileage examples.", symptoms: "- EML and power loss\n- Coolant level dropping (cooler failure)\n- White smoke with sweet smell\n- P0401 EGR code", cause: "The EGR valve carbons up from urban use; the EGR cooler corrodes internally and leaks coolant into the intake. Both are common from 70,000 miles.", fix: "1. Replace EGR valve and cooler together\n2. Flush intake manifold\n3. Cost: £600-1,100 at Land Rover specialist", severity: "severe", mileage_start: 70000, mileage_end: 140000, repair_cost_low: 600, repair_cost_high: 1100, diy_difficulty: "hard", affected_years: "2014-2019", obd_codes: ["P0401","P0128"], published: true },
    { variant_id: vid("disco-sport-mk1-20-td4"), title: "9-Speed ZF Gearbox Shudder", slug: "disco-sport-9spd-shudder", summary: "The Discovery Sport shares the 9-speed ZF gearbox with the Evoque — and shares its shudder problem at low speeds. Software updates partially resolve the issue.", symptoms: "- Shudder when pulling away from standstill\n- Hesitation and jerkiness at low speed\n- Hunting between gears in traffic\n- Clunky engagement from rest", cause: "The 9-speed ZF gearbox requires precise software calibration for smooth low-speed engagement. Early software versions cause the characteristic shudder.", fix: "1. Ensure latest JLR software update applied\n2. ZF gearbox fluid change: £150-250\n3. Mechatronic unit if software doesn't resolve: £1,000-1,800\n4. Full gearbox: £3,500-6,000", severity: "moderate", mileage_start: 1, mileage_end: 80000, repair_cost_low: 100, repair_cost_high: 6000, diy_difficulty: "professional_only", affected_years: "2014-2019", obd_codes: [], published: true },
    { variant_id: vid("disco-sport-mk1-20-td4"), title: "DPF Blockage", slug: "disco-sport-dpf-blockage", summary: "The Discovery Sport TD4 is overwhelmingly used for urban family duties. Short trips prevent DPF regeneration, making it one of the most commonly reported faults.", symptoms: "- DPF warning light\n- Power restriction\n- Oil level rising\n- P2452/P2453 codes", cause: "Short school runs and local errands are the standard Discovery Sport use case — neither allows the DPF to reach regeneration temperature.", fix: "1. Check oil for diesel dilution\n2. Force regen via JLR diagnostic tool\n3. Professional DPF clean: £300-500\n4. Replacement: £900-1,600", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 300, repair_cost_high: 1600, diy_difficulty: "moderate", affected_years: "2014-2019", obd_codes: ["P2452","P2453"], published: true },
    { variant_id: vid("disco-sport-mk1-20-td4"), title: "Rear Differential and Power Transfer Unit Leak", slug: "disco-sport-rear-diff-leak", summary: "The Discovery Sport's rear differential and Power Transfer Unit (PTU) develop oil leaks from output seals with age. Neglected leaks lead to expensive component damage.", symptoms: "- Oil dripping from rear axle or front differential area\n- 4WD system warning\n- Whining from rear differential\n- Reduced traction in 4WD mode", cause: "Output shaft seals in the rear differential and PTU wear and allow gear oil to leak. The PTU in particular is known to run low on oil if the seal is not caught early.", fix: "1. Inspect underside — oil leak location identifies which unit is affected\n2. PTU seal: £200-400. Rear diff seal: £150-300\n3. Unit rebuild if run low on oil: £1,000-2,500\n4. PTU oil change every 60,000 miles — often neglected", severity: "severe", mileage_start: 60000, mileage_end: 130000, repair_cost_low: 150, repair_cost_high: 2500, diy_difficulty: "hard", affected_years: "2014-2019", obd_codes: [], published: true },
  ];

  const insertedFaults = await up("faults", faultRows, "slug");
  console.log(`Faults: ${insertedFaults.length}`);

  const tagMap = {
    "insignia-cdti-timing-chain":     ["timing-chain","engine"],
    "insignia-cdti-dpf":              ["dpf"],
    "insignia-cdti-egr-cooler":       ["egr","cooling"],
    "insignia-cdti-turbo":            ["turbo"],
    "insignia-cdti-injectors":        ["injectors"],
    "zafira-cdti-dpf":                ["dpf"],
    "zafira-cdti-turbo":              ["turbo"],
    "zafira-cdti-egr":                ["egr"],
    "zafira-cdti-dmf":                ["flywheel","clutch"],
    "fabia-mk2-tdi-timing-belt":      ["timing-belt","engine"],
    "fabia-mk2-tdi-dpf":              ["dpf"],
    "fabia-mk2-tdi-egr":              ["egr"],
    "fabia-mk2-tdi-glow-plug":        ["engine"],
    "countryman-n47-timing-chain":    ["timing-chain","engine"],
    "countryman-haldex-failure":      ["gearbox"],
    "countryman-dpf-blockage":        ["dpf"],
    "countryman-egr-swirl":           ["egr","swirl-flaps"],
    "corolla-mk9-dpf-injectors":      ["dpf","injectors"],
    "corolla-mk9-egr":                ["egr"],
    "corolla-mk10-oil-consumption":   ["engine"],
    "corolla-mk10-steering-knock":    ["steering"],
    "punto-multijet-egr":             ["egr"],
    "punto-dualogic-clutch-actuator": ["clutch","gearbox","electrics"],
    "punto-multijet-timing-belt":     ["timing-belt","engine"],
    "punto-mk3-rust":                 ["rust"],
    "evoque-td4-timing-belt":         ["timing-belt","engine"],
    "evoque-9spd-gearbox-shudder":    ["gearbox"],
    "evoque-td4-dpf":                 ["dpf"],
    "evoque-transfer-box-leak":       ["gearbox"],
    "disco-sport-egr-failure":        ["egr","cooling"],
    "disco-sport-9spd-shudder":       ["gearbox"],
    "disco-sport-dpf-blockage":       ["dpf"],
    "disco-sport-rear-diff-leak":     ["gearbox"],
  };

  const tagBySlug   = Object.fromEntries(tags.map(t => [t.slug, t.id]));
  const faultBySlug = Object.fromEntries(insertedFaults.map(f => [f.slug, f.id]));
  const ftRows = [];
  for (const [fs, ts] of Object.entries(tagMap)) {
    const fid = faultBySlug[fs]; if (!fid) continue;
    for (const t of ts) { const tid = tagBySlug[t]; if (tid) ftRows.push({ fault_id: fid, tag_id: tid }); }
  }
  await ins("fault_tags", ftRows, "fault_id,tag_id");
  console.log(`Tag links: ${ftRows.length}`);

  const { count } = await sb.from("faults").select("*", { count: "exact", head: true }).eq("published", true);
  console.log(`\nTotal published faults: ${count}`);
}

run().catch(e => { console.error("Error:", e.message); process.exit(1); });
