/**
 * CKF Phase 2a — Ford + Vauxhall fault depth expansion
 * Run: node lib/seed-phase2a.mjs
 */
import { createClient } from "@supabase/supabase-js";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const ws = require("ws");

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
  { auth: { persistSession: false }, realtime: { transport: ws } }
);

async function upsert(table, rows, conflict) {
  const { data, error } = await supabase.from(table).upsert(rows, { onConflict: conflict, ignoreDuplicates: false }).select();
  if (error) throw new Error(`[${table}] ${error.message}`);
  return data;
}
async function upsertNoReturn(table, rows, conflict) {
  const { error } = await supabase.from(table).upsert(rows, { onConflict: conflict, ignoreDuplicates: true });
  if (error) throw new Error(`[${table}] ${error.message}`);
}
function bySlug(arr, slug) {
  const r = arr.find(x => x.slug === slug);
  if (!r) throw new Error(`Slug not found: "${slug}"`);
  return r;
}

const FAULTS = (variants) => {
  const v = slug => bySlug(variants, slug).id;
  return [

  // ══════════════════════════════════════════════════════════════════════════
  // FORD FIESTA MK7 1.0 ECOBOOST — 4 additional faults
  // ══════════════════════════════════════════════════════════════════════════
  {
    variant_id: v("mk7-10-ecoboost-100"),
    title: "Thermostat Failure and Overheating Risk",
    slug: "fiesta-mk7-ecoboost-thermostat-failure",
    summary: "The plastic thermostat housing on the 1.0 EcoBoost is prone to cracking. A stuck-open thermostat causes the engine to run cold and burn more fuel; a stuck-closed thermostat causes rapid overheating.",
    symptoms: "- Engine takes very long to reach normal temperature\n- Heater blows cold even after 10+ minutes driving\n- Fuel consumption noticeably worse\n- Temperature gauge swings unpredictably\n- Coolant warning light",
    cause: "The thermostat is integrated into a plastic housing bolted to the engine block. The housing develops hairline cracks from thermal cycling, causing coolant to leak. The thermostat element itself fails open or closed with age.",
    fix: "1. Replace thermostat and housing together as a unit — they are sold as an assembly\n2. Drain coolant before removal — use Ford-spec orange coolant on refill\n3. Bleed cooling system carefully — the 1.0 EcoBoost is prone to air locks\n4. Parts cost: £30-60. Labour: 1-2 hours. Total: £80-180 at indie garage",
    severity: "moderate",
    mileage_start: 50000, mileage_end: 100000,
    repair_cost_low: 80, repair_cost_high: 180,
    diy_difficulty: "moderate",
    affected_years: "2012-2018",
    obd_codes: ["P0128", "P0217"],
    published: true,
  },
  {
    variant_id: v("mk7-10-ecoboost-100"),
    title: "Clutch Wear and Judder on Engagement",
    slug: "fiesta-mk7-ecoboost-clutch-wear",
    summary: "The lightweight flywheel and small clutch on the 1.0 EcoBoost are undersized for the turbo torque. Clutch wear and judder on biting point is common from 50,000 miles, especially in urban use.",
    symptoms: "- Juddering or shaking when pulling away from standstill\n- Clutch biting point very high or inconsistent\n- Slipping under hard acceleration\n- Burning smell after hill starts\n- Difficulty finding biting point on hills",
    cause: "The 1.0 EcoBoost produces torque disproportionate to its size, placing higher-than-expected load on the clutch. Urban stop-start driving and hill starts accelerate wear. Some early clutch kits were under-specced.",
    fix: "1. Confirm slip with steady-speed acceleration in high gear — revs rise without speed increase\n2. Replace clutch kit — use Sachs or LuK uprated kit for longevity\n3. Inspect DMF springs at the same time — replace if worn\n4. Labour: 3-4 hours. Total: £400-700",
    severity: "moderate",
    mileage_start: 50000, mileage_end: 90000,
    repair_cost_low: 400, repair_cost_high: 700,
    diy_difficulty: "professional_only",
    affected_years: "2012-2018",
    obd_codes: [],
    published: true,
  },
  {
    variant_id: v("mk7-10-ecoboost-100"),
    title: "Electric Power Steering Failure",
    slug: "fiesta-mk7-ecoboost-eps-failure",
    summary: "The column-mounted electric power steering (EPS) on the Mk7 Fiesta can fail, leaving the driver with very heavy steering. An EPS warning light and fault code confirms the issue.",
    symptoms: "- Orange steering wheel warning light\n- Suddenly heavy steering, especially at low speed\n- Intermittent loss of assistance\n- Clunking or clicking from steering column\n- C1288 or U3000 fault codes",
    cause: "The EPS motor and control module are mounted on the steering column. The motor brushes wear out, the torque sensor fails, or the module develops faults. Heat and vibration accelerate wear on the column-mounted electronics.",
    fix: "1. Read fault codes with a Forscan-compatible reader — confirms EPS fault vs. sensor\n2. Remanufactured steering columns available from £150-250 (exchange)\n3. Programming required after replacement — many independent garages can do this\n4. Full replacement at Ford dealer: £600-900. Independent: £300-500",
    severity: "severe",
    mileage_start: 60000, mileage_end: 120000,
    repair_cost_low: 300, repair_cost_high: 900,
    diy_difficulty: "professional_only",
    affected_years: "2008-2017",
    obd_codes: ["C1288", "U3000"],
    published: true,
  },
  {
    variant_id: v("mk7-10-ecoboost-100"),
    title: "Rear Torsion Beam Corrosion and Squeaking",
    slug: "fiesta-mk7-rear-torsion-beam-corrosion",
    summary: "The rear torsion beam suspension on the Fiesta Mk7 is prone to surface corrosion and the trailing arm bushes wear, causing squeaking and vague rear end feel over bumps.",
    symptoms: "- Squeaking or creaking from rear over speed bumps\n- Clunking from rear on rough roads\n- Uneven tyre wear on rear axle\n- Car tramlines or feels vague on motorway\n- Visible orange rust on rear beam",
    cause: "The unpainted steel torsion beam corrodes in the UK climate. The rubber trailing arm bushes deteriorate with age, allowing movement that creates noise. Not structurally dangerous in early stages but worsens if neglected.",
    fix: "1. Inspect rear beam for corrosion — light surface rust is cosmetic; deep pitting is serious\n2. Replace trailing arm bushes (press fit) — £30-60 parts, £100-150 labour\n3. Wire brush and treat surface corrosion with rust inhibitor and chassis paint\n4. Full beam replacement only needed if structurally compromised: £300-500",
    severity: "minor",
    mileage_start: 70000, mileage_end: 150000,
    repair_cost_low: 100, repair_cost_high: 500,
    diy_difficulty: "moderate",
    affected_years: "2008-2017",
    obd_codes: [],
    published: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // FORD FIESTA MK7 1.5 TDCi — 5 additional faults
  // ══════════════════════════════════════════════════════════════════════════
  {
    variant_id: v("mk7-15-tdci-75"),
    title: "EGR Valve Failure and Intake Carbonisation",
    slug: "fiesta-mk7-tdci-egr-failure",
    summary: "EGR failure on the 1.5 TDCi Fiesta is a common companion to DPF issues. Carbon deposits block the valve and intake manifold, causing power loss and rough running.",
    symptoms: "- EML warning light\n- Power loss, especially 1,500-2,500 RPM\n- Rough idle and hunting\n- Increased fuel consumption\n- P0400, P0401 or P0403 fault codes",
    cause: "The EGR system recirculates exhaust gas for emissions compliance. In low-speed urban use the valve gets coated in carbon. The 1.5 TDCi's compact intake manifold is particularly prone to carbon restriction.",
    fix: "1. Remove EGR valve (2 bolts + electrical connector)\n2. Soak in EGR cleaner, scrub with wire brush, blow dry\n3. Clean intake manifold passages with carb cleaner and pipe brushes\n4. Replacement EGR: £80-200 pattern, £300 OEM\n5. Full job at indie: £200-350",
    severity: "moderate",
    mileage_start: 40000, mileage_end: 90000,
    repair_cost_low: 80, repair_cost_high: 350,
    diy_difficulty: "moderate",
    affected_years: "2013-2017",
    obd_codes: ["P0400", "P0401", "P0403"],
    published: true,
  },
  {
    variant_id: v("mk7-15-tdci-75"),
    title: "Diesel Injector Failure and Rough Running",
    slug: "fiesta-mk7-tdci-injector-failure",
    summary: "Common rail injectors on the 1.5 TDCi can fail, causing misfires, excessive smoke and hard starting. Injector failure can also result in diesel washing the cylinder walls, accelerating engine wear.",
    symptoms: "- Rough idle and shaking\n- Hard starting, especially when cold\n- Blue or white smoke at startup\n- Increased fuel consumption\n- P0201-P0204 injector circuit codes\n- Fuel smell in oil (dipstick smells of diesel)",
    cause: "Common rail injectors have extremely tight tolerances. Wear, contamination from poor-quality fuel, or water ingress causes them to dribble fuel into the cylinder at incorrect times. Each injector is coded to the ECU.",
    fix: "1. Read injector contribution codes — identifies the failing cylinder\n2. Send injectors for ultrasonic cleaning and testing first (£50-80 per injector)\n3. If beyond cleaning, replace faulty injectors — pattern injectors from £100, OEM £300+\n4. New injectors must be coded to ECU by a diesel specialist\n5. Check oil for diesel contamination — oil change needed if present",
    severity: "severe",
    mileage_start: 80000, mileage_end: 160000,
    repair_cost_low: 200, repair_cost_high: 800,
    diy_difficulty: "professional_only",
    affected_years: "2013-2017",
    obd_codes: ["P0201", "P0202", "P0263", "P0266"],
    published: true,
  },
  {
    variant_id: v("mk7-15-tdci-75"),
    title: "Turbocharger Oil Starvation and Failure",
    slug: "fiesta-mk7-tdci-turbo-failure",
    summary: "Turbo failure on the 1.5 TDCi is typically caused by oil feed pipe blockage or low oil levels. The small-displacement turbo spins at extreme speeds and is vulnerable to oil starvation.",
    symptoms: "- Loss of power and boost\n- Loud whining or whirring from turbo\n- Blue smoke on acceleration\n- Oil in intercooler hoses\n- P0299 underboost fault code",
    cause: "The oil feed pipe to the turbocharger can become blocked with sludge, particularly if oil changes have been stretched beyond intervals. Infrequent oil changes cause oil to oxidise and block the small oil feed passages to the turbo bearings.",
    fix: "1. Check oil feed pipe for blockage before condemning the turbo\n2. Check oil level and condition — black, thick oil = neglected maintenance\n3. Replace turbo if bearings are worn (shaft play test)\n4. Flush oil system, fit new filter and fresh oil on any turbo replacement\n5. Turbo replacement: £400-900 fitted",
    severity: "severe",
    mileage_start: 90000, mileage_end: 170000,
    repair_cost_low: 400, repair_cost_high: 900,
    diy_difficulty: "hard",
    affected_years: "2013-2017",
    obd_codes: ["P0299", "P0234"],
    published: true,
  },
  {
    variant_id: v("mk7-15-tdci-75"),
    title: "Glow Plug Failure and Hard Cold Starting",
    slug: "fiesta-mk7-tdci-glow-plug-failure",
    summary: "Failed glow plugs on the 1.5 TDCi cause difficult cold starting, white smoke and misfire on startup. Often overlooked on service schedules, they are a high-mileage wear item.",
    symptoms: "- Long cranking before starting when cold\n- White smoke on cold startup\n- Misfire on start, clears when warm\n- Glow plug warning light on dashboard\n- P0671-P0674 glow plug circuit codes",
    cause: "Glow plugs pre-heat the combustion chamber to aid cold starting. They are a wear item rated for approximately 100,000 miles but can fail earlier. Broken plugs that snap off during removal are a secondary risk.",
    fix: "1. Test each glow plug with a multimeter (resistance test) or dedicated tester\n2. Soak stuck glow plugs in penetrating fluid overnight before removal\n3. Never force — broken glow plugs require specialist extraction tools\n4. Replace all 4 plugs at once — part cost £40-80 for a set (NGK or Bosch)\n5. Full job at indie: £120-250",
    severity: "moderate",
    mileage_start: 80000, mileage_end: 150000,
    repair_cost_low: 120, repair_cost_high: 250,
    diy_difficulty: "moderate",
    affected_years: "2013-2017",
    obd_codes: ["P0671", "P0672", "P0673", "P0674"],
    published: true,
  },
  {
    variant_id: v("mk7-15-tdci-75"),
    title: "Dual Mass Flywheel Judder",
    slug: "fiesta-mk7-tdci-dmf-judder",
    summary: "The 1.5 TDCi Fiesta uses a dual mass flywheel that wears with mileage. DMF wear causes clutch judder and vibration that worsens progressively until the flywheel and clutch are replaced together.",
    symptoms: "- Juddering when pulling away, especially on hills\n- Vibration through clutch pedal\n- Rattling from bellhousing at idle\n- Clunking on gear changes",
    cause: "The DMF absorbs diesel engine vibrations through internal spring dampers. These lose their damping capacity over time. Towing, driving with low fuel (runs hotter), and riding the clutch all accelerate wear.",
    fix: "1. Confirm DMF wear: rattling disappears when clutch pedal depressed\n2. Replace DMF and clutch kit together — never fit a new clutch to a worn DMF\n3. LuK or Sachs DMF + clutch kits recommended\n4. Labour: 4-5 hours. Total: £600-1,000 at indie",
    severity: "moderate",
    mileage_start: 70000, mileage_end: 140000,
    repair_cost_low: 600, repair_cost_high: 1000,
    diy_difficulty: "professional_only",
    affected_years: "2013-2017",
    obd_codes: [],
    published: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // FORD FIESTA MK6 1.25 — 3 additional faults
  // ══════════════════════════════════════════════════════════════════════════
  {
    variant_id: v("mk6-125-82"),
    title: "Timing Chain Tensioner Rattle (Duratec)",
    slug: "fiesta-mk6-timing-chain-rattle",
    summary: "The 1.25 Duratec petrol engine develops a timing chain rattle on cold starts at higher mileages. The hydraulic tensioner loses pressure overnight, causing a brief rattle until oil pressure builds.",
    symptoms: "- Rattling from top of engine on cold start only\n- Noise disappears after 5-10 seconds as oil pressure builds\n- More pronounced in cold weather\n- EML rarely triggered unless timing correlation is off",
    cause: "The chain tensioner is hydraulically actuated and relies on oil pressure. When the engine is cold and oil has drained back from the tensioner, there is a brief moment of slack. Worn chains and guides amplify the noise.",
    fix: "1. If noise disappears quickly when warm — monitor and change oil regularly (every 6,000 miles max)\n2. If noise persists or gets louder: full chain kit replacement\n3. Use 5W-30 fully synthetic to reduce cold-start pressure delay\n4. Chain kit: £150-300 parts. Fitted: £400-600",
    severity: "moderate",
    mileage_start: 80000, mileage_end: 150000,
    repair_cost_low: 400, repair_cost_high: 600,
    diy_difficulty: "hard",
    affected_years: "2008-2012",
    obd_codes: ["P0016", "P0017"],
    published: true,
  },
  {
    variant_id: v("mk6-125-82"),
    title: "Sill and Rear Arch Corrosion",
    slug: "fiesta-mk6-sill-corrosion",
    summary: "The Mk6 Fiesta is now 10+ years old and sill corrosion is increasingly common on UK examples. Bubbling paint along the sill seam and rear arch lip is a typical MOT failure point.",
    symptoms: "- Bubbling or blistering paint on sill seams\n- Visible rust at rear wheel arch lip\n- MOT failure for corrosion to structural sill\n- Paint flaking around door aperture lower edges",
    cause: "Road salt and moisture penetrate the factory seam sealer on the sill box sections. Once rust starts inside the sill, it progresses quickly and is invisible until it breaks through the paint. Cars parked outside year-round deteriorate faster.",
    fix: "1. Inspect sills with a torch — poke suspected areas with a screwdriver (not a magnet)\n2. Light surface rust: treat with rust converter, seal with cavity wax and body sealer\n3. Structural rust: requires panel replacement by a bodywork specialist\n4. Annual Waxoyl or Dinitrol cavity injection significantly slows progression\n5. Budget £300-1,500 depending on severity",
    severity: "moderate",
    mileage_start: 1, mileage_end: 999999,
    repair_cost_low: 300, repair_cost_high: 1500,
    diy_difficulty: "hard",
    affected_years: "2008-2012",
    obd_codes: [],
    published: true,
  },
  {
    variant_id: v("mk6-125-82"),
    title: "Clutch Wear and High Biting Point",
    slug: "fiesta-mk6-clutch-wear",
    summary: "Clutch wear on the Fiesta Mk6 1.25 is a regular occurrence at 60,000-90,000 miles. The biting point migrates towards the top of the pedal travel as the friction plate wears down.",
    symptoms: "- Biting point near top of clutch pedal travel\n- Juddering on gentle pull-away\n- Slipping under hard acceleration in high gears\n- Burning smell after heavy clutch use",
    cause: "Normal wear on the clutch friction plate. Accelerated by city driving, hill starts and learner or newly-passed drivers. The cable-operated clutch on early Mk6 variants stretches with use, exaggerating the high biting point.",
    fix: "1. Check clutch cable adjustment first on cable-operated versions — often resolves high biting point\n2. Full clutch replacement if friction plate is worn — Sachs or LuK kit recommended\n3. Inspect rear crankshaft oil seal at the same time — replace if leaking onto clutch\n4. Labour: 3 hours. Total: £350-550",
    severity: "moderate",
    mileage_start: 60000, mileage_end: 100000,
    repair_cost_low: 350, repair_cost_high: 550,
    diy_difficulty: "professional_only",
    affected_years: "2008-2012",
    obd_codes: [],
    published: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // FORD FOCUS MK2 1.6 TDCi — 3 additional faults
  // ══════════════════════════════════════════════════════════════════════════
  {
    variant_id: v("mk2-16-tdci"),
    title: "Diesel Particulate Filter Blockage",
    slug: "focus-mk2-tdci-dpf-blockage",
    summary: "DPF blockage on the Focus Mk2 1.6 TDCi is one of the most common complaints. Ford fitted DPFs from 2007 onwards and city-driven examples struggle to complete the regeneration cycle.",
    symptoms: "- DPF warning light (amber)\n- Reduced power and limp mode\n- Engine running rough under load\n- Strong diesel smell from exhaust\n- Oil level above maximum on dipstick (diesel dilution from failed regens)",
    cause: "The DPF requires sustained motorway speeds to regenerate. Urban-only Focus diesels accumulate soot faster than passive regen clears it. Failed active regens result in diesel contaminating the engine oil.",
    fix: "1. Check oil level first — if above max and smells of diesel, change oil immediately\n2. Forced regen via OBD (Forscan can trigger this)\n3. Professional DPF clean: £200-300\n4. If blocked beyond cleaning: replacement £500-1,000\n5. Prevention: 20-min motorway run every 2 weeks",
    severity: "moderate",
    mileage_start: 40000, mileage_end: 90000,
    repair_cost_low: 200, repair_cost_high: 1000,
    diy_difficulty: "moderate",
    affected_years: "2007-2011",
    obd_codes: ["P2452", "P2453", "P246C"],
    published: true,
  },
  {
    variant_id: v("mk2-16-tdci"),
    title: "Injector Seal Failure and Diesel Weeping",
    slug: "focus-mk2-tdci-injector-seals",
    summary: "The copper seating washers and O-ring seals on the 1.6 TDCi injectors harden with heat cycling and allow diesel to weep past the injector body. This causes a fuel smell and carbon build-up around the injector tops.",
    symptoms: "- Diesel smell in engine bay after running\n- Carbon deposits around injector bodies\n- Slight fuel weep visible at injector base\n- Rough running if leak is significant\n- Loss of injector clamping pressure",
    cause: "The copper crush washers and rubber O-rings that seal the injectors against the head degrade with repeated heat cycles. Diesel weeps past the failing seal, carbonises, and eventually allows unmetered fuel into the combustion chamber.",
    fix: "1. Inspect injector tops — black carbonised residue confirms the leak\n2. Remove injectors, clean bores, fit new copper washers and O-rings (£5-15 per set)\n3. Re-torque injector clamps to spec\n4. Full job at indie: £150-300 depending on how many injectors need resealing",
    severity: "moderate",
    mileage_start: 70000, mileage_end: 140000,
    repair_cost_low: 150, repair_cost_high: 300,
    diy_difficulty: "hard",
    affected_years: "2004-2011",
    obd_codes: [],
    published: true,
  },
  {
    variant_id: v("mk2-16-tdci"),
    title: "Swirl Flap Motor Failure",
    slug: "focus-mk2-tdci-swirl-flap-motor",
    summary: "The intake manifold swirl flaps on the 1.6 TDCi are actuated by an electric motor. When the motor fails, the car goes into limp mode. Unlike the N47 BMW, the flaps rarely break off — but the motor commonly burns out.",
    symptoms: "- EML light and power restriction\n- P1000 or P2004/P2006 intake manifold codes\n- Loss of low-end torque\n- Engine management warning with no other symptoms",
    cause: "The swirl flap actuator motor is an underpowered unit that can burn out after years of constant use. The flaps themselves can also seize in position due to carbon build-up on the spindles.",
    fix: "1. Read codes — P2004/P2006 confirm swirl flap position fault\n2. Try cleaning the flap spindles with carb cleaner before condemning the motor\n3. Replacement motor: £80-150 (OEM Pierburg unit)\n4. Alternatively fit blanking plates if flaps are beyond cleaning (£30)\n5. Full replacement at indie: £200-350",
    severity: "moderate",
    mileage_start: 60000, mileage_end: 120000,
    repair_cost_low: 100, repair_cost_high: 350,
    diy_difficulty: "moderate",
    affected_years: "2004-2011",
    obd_codes: ["P2004", "P2006", "P2008"],
    published: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // FORD FOCUS MK3 1.0 EcoBoost — 5 faults
  // ══════════════════════════════════════════════════════════════════════════
  {
    variant_id: v("mk3-10-ecoboost"),
    title: "Timing Chain Stretch and Tensioner Failure",
    slug: "focus-mk3-ecoboost-timing-chain",
    summary: "The Focus Mk3 1.0 EcoBoost shares the same timing chain vulnerability as the Fiesta Mk7. Pre-2016 engines are the highest risk — chain rattle on cold start must be investigated immediately.",
    symptoms: "- Rattling from front of engine on cold start\n- EML with P0016, P0017\n- Rough running or misfires\n- Chain slap sound under rapid acceleration",
    cause: "The plastic tensioner and guides wear prematurely. The chain stretches, eventually causing cam/crank timing to drift. Ford issued a TSB acknowledging the issue on 2012-2015 production engines.",
    fix: "1. Timing chain kit replacement (chain, tensioner, guides, VCT solenoid)\n2. Check TSB history — ask if the timing chain has already been replaced under Ford goodwill\n3. Use 5W-30 fully synthetic, max 6,000-mile oil change intervals going forward\n4. Cost: £600-1,200 fitted",
    severity: "critical",
    mileage_start: 40000, mileage_end: 100000,
    repair_cost_low: 600, repair_cost_high: 1200,
    diy_difficulty: "hard",
    affected_years: "2011-2015",
    obd_codes: ["P0016", "P0017", "P0011"],
    published: true,
  },
  {
    variant_id: v("mk3-10-ecoboost"),
    title: "Coolant Loss from Integrated Exhaust Manifold",
    slug: "focus-mk3-ecoboost-coolant-loss",
    summary: "The 1.0 EcoBoost's unique integrated exhaust manifold/cylinder head design causes head gasket stress. Coolant loss without visible leaks is a known issue on higher-mileage Focus Mk3 examples.",
    symptoms: "- Coolant level drops without visible external leak\n- Sweet smell from engine bay\n- White smoke on cold starts\n- Overheating warning on longer journeys\n- Heater temperature inconsistent",
    cause: "Heat from the integral exhaust manifold repeatedly stresses the head gasket. The gasket can fail between the water jacket and combustion chamber. Some engines also have casting defects in the coolant jacket.",
    fix: "1. Block test for combustion gases in coolant (test kit £10 — turns yellow to green)\n2. Head gasket replacement required if positive\n3. Pressure test system first to rule out external leaks\n4. Use updated MLS head gasket on reassembly\n5. Cost: £500-900 at indie",
    severity: "severe",
    mileage_start: 60000, mileage_end: 120000,
    repair_cost_low: 500, repair_cost_high: 900,
    diy_difficulty: "hard",
    affected_years: "2011-2018",
    obd_codes: ["P0128", "P0217"],
    published: true,
  },
  {
    variant_id: v("mk3-10-ecoboost"),
    title: "Turbocharger Boost Leak from Intercooler Pipe",
    slug: "focus-mk3-ecoboost-boost-leak",
    summary: "Boost pressure leaks from the plastic intercooler pipes and clamp connections on the 1.0 EcoBoost are common. A leak causes a noticeable flat spot and loss of performance under boost.",
    symptoms: "- Flat spot under acceleration, especially 2,000-3,500 RPM\n- Hissing noise under hard acceleration\n- P0299 underboost code\n- Turbo spools up but boost doesn't arrive",
    cause: "The plastic boost pipes and rubber joiners deteriorate with age and heat. The clamps loosen over time. On turbo-charged small engines the pressure differential is high and any weakness in the plumbing causes a noticeable power loss.",
    fix: "1. With engine running, feel along all boost pipes for escaping air under acceleration\n2. Common failure points: elbow at throttle body, pipe to intercooler, turbo outlet\n3. Silicone replacement hoses available for £30-80 (more durable than OEM plastic)\n4. Fix is usually DIY: hose clamps and replacement pipes",
    severity: "moderate",
    mileage_start: 50000, mileage_end: 120000,
    repair_cost_low: 30, repair_cost_high: 150,
    diy_difficulty: "easy",
    affected_years: "2011-2018",
    obd_codes: ["P0299"],
    published: true,
  },
  {
    variant_id: v("mk3-10-ecoboost"),
    title: "Water Pump Failure (Belt-Driven Internal)",
    slug: "focus-mk3-ecoboost-water-pump",
    summary: "The 1.0 EcoBoost uses a belt-driven water pump. When the pump fails, coolant circulation stops and the engine overheats rapidly. Because it is inside the engine, early detection requires vigilance.",
    symptoms: "- Sudden rapid overheating\n- Coolant temperature spike with no warning\n- Loss of coolant from expansion tank\n- Water pump bearing noise (grinding)\n- Coolant leak at front of engine",
    cause: "The water pump impeller and shaft bearing wear with mileage. When the bearing fails the pump leaks; when the impeller fails cooling stops. Ford recommends replacement at 125,000 miles but failures occur earlier.",
    fix: "1. Never continue driving an overheating 1.0 EcoBoost — stop immediately\n2. Water pump is accessible from the front of the engine (not timing chain side)\n3. Replace water pump, thermostat and coolant together\n4. Cost: £250-500 fitted at indie garage",
    severity: "severe",
    mileage_start: 80000, mileage_end: 140000,
    repair_cost_low: 250, repair_cost_high: 500,
    diy_difficulty: "moderate",
    affected_years: "2011-2018",
    obd_codes: ["P0217", "P0128"],
    published: true,
  },
  {
    variant_id: v("mk3-10-ecoboost"),
    title: "Rear Axle Beam Bush Deterioration",
    slug: "focus-mk3-rear-axle-bush",
    summary: "The rear axle bushes on the Focus Mk3 deteriorate with age, particularly on higher-mileage cars. Worn bushes cause a knocking noise from the rear and vague handling — an MOT advisory that becomes a failure if neglected.",
    symptoms: "- Knocking from rear over bumps or on turning\n- Rear end feels vague or loose at motorway speeds\n- Uneven tyre wear on rear axle\n- MOT advisory: rear axle bushes worn",
    cause: "The rubber-bonded rear axle bushes absorb road impacts and allow controlled axle movement. UK road surfaces and the car's age cause the rubber to harden, crack and eventually allow metal-to-metal contact.",
    fix: "1. Inspect bushes visually — cracked, split or deformed rubber confirms failure\n2. Replacement bushes can be pressed in — hydraulic press required\n3. Polybush polyurethane alternatives available if you want longer life\n4. Cost: £150-300 at indie garage for both sides",
    severity: "minor",
    mileage_start: 70000, mileage_end: 140000,
    repair_cost_low: 150, repair_cost_high: 300,
    diy_difficulty: "moderate",
    affected_years: "2011-2018",
    obd_codes: [],
    published: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // FORD FOCUS MK3 1.6 TDCi — 6 faults
  // ══════════════════════════════════════════════════════════════════════════
  {
    variant_id: v("mk3-16-tdci"),
    title: "DPF Blockage and Forced Regeneration Failure",
    slug: "focus-mk3-tdci-dpf-blockage",
    summary: "DPF blockage is the most reported issue on the Focus Mk3 1.6 TDCi. City driving prevents regeneration, and the DPF warning light becomes a familiar sight for urban Focus diesel owners.",
    symptoms: "- DPF warning light illuminated\n- Power loss and limp mode\n- Oil level above maximum (diesel contamination)\n- Black smoke from exhaust under load\n- P2452 or P2453 fault codes",
    cause: "Short urban journeys prevent the exhaust reaching the 550°C needed for regeneration. The ECU attempts active regen by injecting extra diesel into the exhaust — if this fails, diesel ends up in the engine oil.",
    fix: "1. Check oil immediately — change if contaminated with diesel\n2. Attempt forced regen via Forscan (free) or a diesel specialist\n3. Professional DPF clean if soot load too high for regen: £200-350\n4. Replacement if damaged: £500-1,000\n5. Adopt at least one 30-min motorway run per week",
    severity: "moderate",
    mileage_start: 40000, mileage_end: 90000,
    repair_cost_low: 200, repair_cost_high: 1000,
    diy_difficulty: "moderate",
    affected_years: "2011-2018",
    obd_codes: ["P2452", "P2453", "P246C"],
    published: true,
  },
  {
    variant_id: v("mk3-16-tdci"),
    title: "EGR Valve and Cooler Failure",
    slug: "focus-mk3-tdci-egr-failure",
    summary: "The EGR valve and cooler on the Mk3 Focus 1.6 TDCi are known to fail together. EGR cooler failure can cause coolant to enter the intake — a more serious failure than a simple blocked valve.",
    symptoms: "- EML with power restriction\n- Coolant loss without visible external leak\n- P0401 EGR flow fault\n- White smoke with sweet smell\n- Loss of coolant from expansion tank",
    cause: "The EGR cooler corrodes internally and allows coolant to leak into the intake manifold. Combined with the valve itself carbonising, these are commonly found together on higher-mileage examples.",
    fix: "1. Replace EGR cooler and valve together on any high-mileage example\n2. Flush intake manifold of coolant residue before restarting\n3. OEM Pierburg/Valeo cooler recommended over pattern parts\n4. Cost: £400-700 at an indie diesel specialist",
    severity: "severe",
    mileage_start: 60000, mileage_end: 120000,
    repair_cost_low: 400, repair_cost_high: 700,
    diy_difficulty: "hard",
    affected_years: "2011-2018",
    obd_codes: ["P0401", "P0402", "P0128"],
    published: true,
  },
  {
    variant_id: v("mk3-16-tdci"),
    title: "Turbocharger Failure",
    slug: "focus-mk3-tdci-turbocharger-failure",
    summary: "The turbocharger on the Focus Mk3 1.6 TDCi is vulnerable to bearing wear from oil sludge and extended service intervals. Failure typically presents as a sudden loss of power with a loud noise.",
    symptoms: "- Loud whining or screeching from engine bay\n- Loss of power and boost pressure\n- Blue smoke on acceleration\n- Oil found in intercooler or air intake\n- P0299 underboost code",
    cause: "Oil sludge from infrequent oil changes blocks the turbo oil feed pipe. Bearings starved of oil fail rapidly. The turbo shaft can then contact the housing, causing catastrophic failure.",
    fix: "1. Check oil feed pipe before replacing turbo — may simply be blocked\n2. Check shaft play: grab compressor wheel and test for radial play\n3. Turbo replacement: remanufactured unit £300-600, new OEM £800+\n4. Always flush oil system and use fresh oil when fitting a new turbo\n5. Fitted cost at indie: £500-1,000",
    severity: "severe",
    mileage_start: 90000, mileage_end: 160000,
    repair_cost_low: 500, repair_cost_high: 1000,
    diy_difficulty: "hard",
    affected_years: "2011-2018",
    obd_codes: ["P0299", "P0234"],
    published: true,
  },
  {
    variant_id: v("mk3-16-tdci"),
    title: "Dual Mass Flywheel Failure",
    slug: "focus-mk3-tdci-dmf-failure",
    summary: "DMF failure on the Focus Mk3 1.6 TDCi is common from 80,000 miles. The dual mass flywheel is essential to smooth diesel vibration and when it fails, the shudder becomes impossible to ignore.",
    symptoms: "- Juddering and vibration when pulling away\n- Rattling from gearbox at idle, clears with clutch pressed\n- Vibration through gear lever at idle\n- Clunking on hard gear changes",
    cause: "The internal spring dampers of the DMF lose their effectiveness with mileage and use. City driving with frequent stop-start use accelerates wear faster than motorway driving.",
    fix: "1. Always replace DMF and clutch kit at the same time\n2. LuK or Sachs OEM-quality kits only — avoid cheap pattern parts\n3. Solid flywheel conversion is an option for high-mileage cars\n4. Labour: 4-6 hours. Total cost: £700-1,100",
    severity: "moderate",
    mileage_start: 80000, mileage_end: 150000,
    repair_cost_low: 700, repair_cost_high: 1100,
    diy_difficulty: "professional_only",
    affected_years: "2011-2018",
    obd_codes: [],
    published: true,
  },
  {
    variant_id: v("mk3-16-tdci"),
    title: "Injector Failure and High Return Fuel Pressure",
    slug: "focus-mk3-tdci-injector-failure",
    summary: "Common rail injector failure on the Focus Mk3 TDCi causes rough running, misfires and in severe cases, diesel contamination of the engine oil. Worn injectors dribble fuel continuously.",
    symptoms: "- Rough idle and shaking\n- White smoke on startup\n- Hard starting from cold\n- Rising oil level (diesel in oil)\n- P0201-P0204 injector codes",
    cause: "Common rail injectors wear at their control valve and needle seats over time, allowing uncontrolled fuel to dribble into the cylinder. Poor-quality or contaminated fuel accelerates wear.",
    fix: "1. Contribution balance test identifies worst injectors\n2. Send for ultrasonic clean and test before replacing\n3. Replacement injectors must be coded to ECU\n4. Check and change oil if diesel contamination found\n5. Cost per injector: £150-400 supply and fit",
    severity: "severe",
    mileage_start: 90000, mileage_end: 170000,
    repair_cost_low: 200, repair_cost_high: 1000,
    diy_difficulty: "professional_only",
    affected_years: "2011-2018",
    obd_codes: ["P0201", "P0202", "P0263"],
    published: true,
  },
  {
    variant_id: v("mk3-16-tdci"),
    title: "Glow Plug Failure and White Smoke on Cold Start",
    slug: "focus-mk3-tdci-glow-plug",
    summary: "Glow plug failure on the Focus Mk3 TDCi is a common higher-mileage issue. Failed plugs cause white smoke and rough running when cold, clearing quickly once the engine reaches temperature.",
    symptoms: "- White smoke on startup in cold weather\n- Long cranking before the engine fires\n- Rough running for first 2-3 minutes\n- Glow plug warning light\n- P0671-P0674 codes",
    cause: "Glow plugs are wear items. The Focus 1.6 TDCi plugs are known to seize in the head at high mileage, making removal risky. Prevention is better than cure.",
    fix: "1. Test plugs with a multimeter — open circuit = failed plug\n2. Soak in penetrating fluid for 24 hours before removal attempt\n3. Never force a seized glow plug — extraction is specialist work\n4. Replace all four at once — NGK or Bosch plugs recommended\n5. Cost: £100-250 depending on plug removal difficulty",
    severity: "moderate",
    mileage_start: 80000, mileage_end: 150000,
    repair_cost_low: 100, repair_cost_high: 250,
    diy_difficulty: "moderate",
    affected_years: "2011-2018",
    obd_codes: ["P0671", "P0672", "P0673", "P0674"],
    published: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // VAUXHALL CORSA D 1.3 CDTi — 4 additional faults
  // ══════════════════════════════════════════════════════════════════════════
  {
    variant_id: v("corsa-d-13-cdti"),
    title: "Turbocharger Failure and Oil Starvation",
    slug: "corsa-d-cdti-turbo-failure",
    summary: "Turbo failure on the Fiat/Vauxhall 1.3 CDTi is a documented weakness, particularly when oil change intervals have been extended. The small variable-vane turbo is sensitive to oil quality.",
    symptoms: "- Loss of power and boost\n- Loud whining noise from turbo under load\n- Blue smoke on acceleration\n- Oil in intercooler pipes\n- P0299 underboost code",
    cause: "The variable-vane actuator on the turbocharger can stick with carbon deposits, causing the vanes to seize. Combined with oil starvation from sludged feed pipes, this causes bearing failure.",
    fix: "1. Check VNT actuator operation first — a stuck vane is cheaper to fix than a new turbo\n2. Clean actuator and vanes with carb cleaner if sticky (not seized)\n3. Replacement turbo (remanufactured): £250-450\n4. Flush oil system on installation — old sludge will kill a new turbo within weeks\n5. Fitted: £450-750 at indie",
    severity: "severe",
    mileage_start: 80000, mileage_end: 150000,
    repair_cost_low: 450, repair_cost_high: 750,
    diy_difficulty: "hard",
    affected_years: "2006-2014",
    obd_codes: ["P0299", "P0234"],
    published: true,
  },
  {
    variant_id: v("corsa-d-13-cdti"),
    title: "Diesel Fuel Injection Pump Failure",
    slug: "corsa-d-cdti-fuel-pump-failure",
    summary: "The high-pressure fuel pump on the 1.3 CDTi can fail, causing hard starting, rough running and eventually preventing the engine from starting. It is an expensive repair relative to the car's value.",
    symptoms: "- Very hard starting, multiple cranking attempts needed\n- Rough idle on startup, clears when warm\n- P0087 low fuel pressure code\n- Engine cuts out under hard acceleration\n- White smoke from exhaust",
    cause: "The HPFP wears internally over time. Fuel contamination and infrequent filter changes accelerate wear. Early failures have also been linked to diesel quality — always use a reputable fuel supplier.",
    fix: "1. Check fuel filter first — blocked filter causes similar symptoms\n2. Confirm with fuel pressure test (a workshop tool)\n3. Replacement pump: £300-600 supply only\n4. Must be set up by a diesel specialist — fuel calibration required\n5. Consider the car's value carefully before authorising this repair",
    severity: "severe",
    mileage_start: 100000, mileage_end: 180000,
    repair_cost_low: 500, repair_cost_high: 900,
    diy_difficulty: "professional_only",
    affected_years: "2006-2014",
    obd_codes: ["P0087", "P0093"],
    published: true,
  },
  {
    variant_id: v("corsa-d-13-cdti"),
    title: "Injector Failure and Black Smoke",
    slug: "corsa-d-cdti-injector-failure",
    summary: "Injector failure on the 1.3 CDTi causes rough running, misfires and black smoke under acceleration. The piezoelectric injectors used in this engine are expensive to replace.",
    symptoms: "- Black smoke under acceleration\n- Rough idle and misfires\n- Uneven power delivery\n- Fuel economy drops noticeably\n- P0201-P0204 fault codes",
    cause: "The 1.3 CDTi uses piezoelectric injectors that wear at their needle seats. Contaminated fuel or extended service intervals accelerate deterioration. Each injector is calibrated individually.",
    fix: "1. Contribution test identifies failing cylinder\n2. Send injectors for professional cleaning and calibration first (£60-100 each)\n3. If beyond repair, replacement injectors must be coded to ECU\n4. Cost per injector fitted: £200-400\n5. Replace fuel filter at same time",
    severity: "severe",
    mileage_start: 90000, mileage_end: 170000,
    repair_cost_low: 300, repair_cost_high: 900,
    diy_difficulty: "professional_only",
    affected_years: "2006-2014",
    obd_codes: ["P0201", "P0202", "P0263", "P0266"],
    published: true,
  },
  {
    variant_id: v("corsa-d-13-cdti"),
    title: "Glow Plug Failure and Difficult Cold Starting",
    slug: "corsa-d-cdti-glow-plug-failure",
    summary: "Failed glow plugs on the Corsa D 1.3 CDTi cause white smoke and hard cold starting. The 1.3-litre engine has a small combustion chamber that relies heavily on glow plugs in cold UK winters.",
    symptoms: "- White smoke on cold start\n- Long cranking before engine fires when cold\n- Rough running for first minute\n- Glow plug warning light\n- P0671-P0674 codes",
    cause: "Glow plugs are consumable items. The 1.3 CDTi uses fragile plugs that must be pre-soaked in penetrating fluid before removal to avoid snapping. Seized plugs require specialist extraction.",
    fix: "1. Test all four plugs with multimeter — 0.5-2 ohm = good, open = dead\n2. Soak with Plus Gas or WD40 24 hours before removal attempt\n3. Replace as a full set — NGK or Champion plugs only\n4. Cost: £100-200 including labour\n5. If one snaps in the head: specialist extraction required (£200-400 extra)",
    severity: "moderate",
    mileage_start: 70000, mileage_end: 140000,
    repair_cost_low: 100, repair_cost_high: 400,
    diy_difficulty: "moderate",
    affected_years: "2006-2014",
    obd_codes: ["P0671", "P0672"],
    published: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // VAUXHALL CORSA D 1.2 — 4 additional faults
  // ══════════════════════════════════════════════════════════════════════════
  {
    variant_id: v("corsa-d-12-85"),
    title: "Timing Chain Tensioner Rattle",
    slug: "corsa-d-12-timing-chain-rattle",
    summary: "The Z12XEP 1.2-litre engine develops a timing chain rattle on cold starts. The hydraulic tensioner weakens with age and the chain slaps until oil pressure builds — a warning sign that should not be ignored.",
    symptoms: "- Chain rattle on cold start, disappears within 10 seconds\n- More pronounced in cold weather\n- Occasional EML with P0016\n- Metallic ticking from top of engine",
    cause: "The hydraulic tensioner relies on oil pressure to maintain chain tension. At cold idle the pressure takes a moment to build. A worn chain and weak tensioner amplify the brief slack into an audible rattle.",
    fix: "1. Shorten oil change interval to 6,000 miles — fresh oil maintains better cold pressure\n2. Monitor closely — if rattle lasts longer than 10 seconds or is getting louder, act\n3. Full timing chain kit: chain, guides, tensioner — £150-250 parts\n4. Fitted cost: £400-600",
    severity: "moderate",
    mileage_start: 80000, mileage_end: 150000,
    repair_cost_low: 400, repair_cost_high: 600,
    diy_difficulty: "hard",
    affected_years: "2006-2014",
    obd_codes: ["P0016", "P0017"],
    published: true,
  },
  {
    variant_id: v("corsa-d-12-85"),
    title: "Front Wheel Bearing Wear",
    slug: "corsa-d-12-wheel-bearing",
    summary: "Front wheel bearing failure is very common on the Corsa D. The sealed bearing units wear from around 60,000 miles, producing a characteristic humming drone that changes pitch with steering input.",
    symptoms: "- Droning or humming noise that increases with speed\n- Noise changes when steering left or right\n- Vibration through steering wheel\n- Noise worse on one side — load transfers when cornering",
    cause: "The Corsa D uses pressed-in sealed bearing units. They wear normally with mileage and are accelerated by kerbing, potholes and misaligned tracking. The front bearings take additional load when braking.",
    fix: "1. Jack the suspect wheel and check for play at 12 and 6 o'clock\n2. Replacement requires a hydraulic press to remove and install bearing\n3. Use quality brands: FAG, SKF or Timken — not cheap pattern bearings\n4. Cost: £120-220 per side fitted at indie",
    severity: "moderate",
    mileage_start: 60000, mileage_end: 100000,
    repair_cost_low: 120, repair_cost_high: 220,
    diy_difficulty: "moderate",
    affected_years: "2006-2014",
    obd_codes: [],
    published: true,
  },
  {
    variant_id: v("corsa-d-12-85"),
    title: "Throttle Body Contamination and Rough Idle",
    slug: "corsa-d-12-throttle-body",
    summary: "The Corsa D 1.2 petrol suffers from throttle body contamination from crankcase vapours. Carbon and oil deposits coat the throttle blade and idle control passages, causing hunting idle and poor response.",
    symptoms: "- Hunting or fluctuating idle (revs rise and fall)\n- Poor throttle response at low speeds\n- Hesitation on light acceleration\n- P0506 or P0507 idle control fault codes",
    cause: "The PCV system routes crankcase vapour through the throttle body. Over time, the oil in the vapour deposits carbon on the throttle blade and the air bypass channels, restricting airflow at idle.",
    fix: "1. Remove the throttle body (2-4 bolts on most variants)\n2. Clean with carb cleaner and a cotton bud — be thorough around the blade edge\n3. Do not use harsh metal scrapers — damage the blade coating\n4. Throttle body relearn procedure needed after cleaning on some variants\n5. DIY job: 1 hour. Cost: just a can of carb cleaner",
    severity: "minor",
    mileage_start: 50000, mileage_end: 120000,
    repair_cost_low: 50, repair_cost_high: 200,
    diy_difficulty: "easy",
    affected_years: "2006-2014",
    obd_codes: ["P0506", "P0507"],
    published: true,
  },
  {
    variant_id: v("corsa-d-12-85"),
    title: "Power Steering Failure (Electric Rack)",
    slug: "corsa-d-12-power-steering-failure",
    summary: "The electric power steering on later Corsa D models can fail, causing heavy steering with a warning light. The EPS motor on the steering column is the common failure point.",
    symptoms: "- Orange steering wheel warning light\n- Heavy steering at low speed and when parking\n- Intermittent power steering assistance\n- Clunking from steering column\n- C0000 or U0001 EPS fault codes",
    cause: "The column-mounted EPS motor and control unit fail due to electrical issues, brush wear or circuit board faults. Heat and vibration from the engine bay area cause premature electronics failure.",
    fix: "1. Check fuse box for blown EPS fuse (quick first check)\n2. Remanufactured steering column available exchange from £120-200\n3. Programming may be required after replacement\n4. Full dealer replacement: £500-700. Independent: £250-450",
    severity: "moderate",
    mileage_start: 70000, mileage_end: 130000,
    repair_cost_low: 250, repair_cost_high: 700,
    diy_difficulty: "professional_only",
    affected_years: "2006-2014",
    obd_codes: ["C0000", "C1288"],
    published: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // VAUXHALL CORSA E 1.4 — 5 faults
  // ══════════════════════════════════════════════════════════════════════════
  {
    variant_id: v("corsa-e-14-90"),
    title: "Timing Chain Tensioner Failure",
    slug: "corsa-e-14-timing-chain",
    summary: "The A14NET 1.4 turbo engine in the Corsa E is known for timing chain noise from the tensioner. Like many modern small-displacement turbo engines, the timing chain is not a lifetime component.",
    symptoms: "- Rattling on cold start from front of engine\n- Noise lasts longer as chain wear progresses\n- P0016, P0017 timing correlation codes\n- EML illuminated",
    cause: "The chain tensioner wears its hydraulic mechanism and loses the ability to maintain consistent tension. The chain then slaps against the guides. Common on cars with extended oil change intervals.",
    fix: "1. Full timing chain kit replacement — chain, tensioner, guides\n2. Use 5W-30 fully synthetic oil, 6,000-mile intervals maximum\n3. Cost: £500-900 fitted",
    severity: "critical",
    mileage_start: 60000, mileage_end: 120000,
    repair_cost_low: 500, repair_cost_high: 900,
    diy_difficulty: "professional_only",
    affected_years: "2014-2019",
    obd_codes: ["P0016", "P0017"],
    published: true,
  },
  {
    variant_id: v("corsa-e-14-90"),
    title: "Coolant Loss and Head Gasket Failure",
    slug: "corsa-e-14-coolant-loss",
    summary: "The Corsa E 1.4 turbo shares the head gasket vulnerability of its predecessors. Coolant loss without visible external leaks is a red flag that demands immediate investigation.",
    symptoms: "- Coolant level dropping over weeks\n- Sweet smell from engine bay\n- White smoke on startup\n- Overheating warning\n- Mayonnaise under oil cap",
    cause: "The 1.4 turbo engine's head gasket is stressed by turbo heat. The gasket between the water jacket and combustion chamber fails, allowing coolant to be burned or expelled through the exhaust.",
    fix: "1. Block test for combustion gases in coolant\n2. Pressure test system for external leaks first\n3. Head gasket replacement with new MLS gasket\n4. Check head for warping — skim if more than 0.05mm deviation\n5. Cost: £500-800 at indie",
    severity: "severe",
    mileage_start: 60000, mileage_end: 120000,
    repair_cost_low: 500, repair_cost_high: 800,
    diy_difficulty: "hard",
    affected_years: "2014-2019",
    obd_codes: ["P0128", "P0217"],
    published: true,
  },
  {
    variant_id: v("corsa-e-14-90"),
    title: "Throttle Body Carbon Contamination",
    slug: "corsa-e-14-throttle-body",
    summary: "PCV vapour deposits cause the Corsa E 1.4 throttle body to become coated in carbon. The result is a lumpy idle and hesitation, particularly noticeable on a cold start.",
    symptoms: "- Lumpy, fluctuating idle when cold\n- Hesitation under light throttle\n- Improved after a hard run\n- P0506/P0507 idle speed codes",
    cause: "Direct-injection and PCV vapour routing causes oil deposits to accumulate on the throttle plate and bypass passages. The deposits restrict airflow and upset idle air calculation.",
    fix: "1. Remove and clean throttle body with carb cleaner\n2. Perform throttle body relearn via OBD after cleaning\n3. DIY: 1 hour, cost of carb cleaner\n4. Replacement if damaged: £100-200",
    severity: "minor",
    mileage_start: 40000, mileage_end: 100000,
    repair_cost_low: 50, repair_cost_high: 200,
    diy_difficulty: "easy",
    affected_years: "2014-2019",
    obd_codes: ["P0506", "P0507"],
    published: true,
  },
  {
    variant_id: v("corsa-e-14-90"),
    title: "Turbocharger Actuator Failure",
    slug: "corsa-e-14-turbo-actuator",
    summary: "The electronic boost pressure actuator on the Corsa E 1.4 turbo can fail, causing loss of boost and limp mode. The actuator controls variable boost and is a known failure point on this generation.",
    symptoms: "- Loss of boost and power, especially above 2,500 RPM\n- Limp mode activation\n- P0234 overboost or P0299 underboost codes\n- Turbo spools but boost does not build normally",
    cause: "The electronic wastegate actuator motor and its control circuit fail with age. Cold weather and moisture ingress accelerate the failure of the actuator electronics.",
    fix: "1. Check actuator rod for physical damage or seizure first\n2. Replacement actuator: £100-250 (often sold as turbo assembly)\n3. Actuator-only replacement requires calibration via OBD after fitting\n4. Fitted at indie: £300-600",
    severity: "moderate",
    mileage_start: 60000, mileage_end: 120000,
    repair_cost_low: 300, repair_cost_high: 600,
    diy_difficulty: "hard",
    affected_years: "2014-2019",
    obd_codes: ["P0234", "P0299"],
    published: true,
  },
  {
    variant_id: v("corsa-e-14-90"),
    title: "Rear Sill Corrosion",
    slug: "corsa-e-14-rear-sill-corrosion",
    summary: "The Corsa E, like its predecessors, is susceptible to sill box section corrosion. UK salt and moisture attack the seam-welded sills from inside, causing bubbling and structural deterioration.",
    symptoms: "- Paint bubbling at sill seam lines\n- Rust visible at rear wheel arch lips\n- Soft spots in sill when pressed\n- MOT failure for corrosion",
    cause: "Factory undersealing on Corsa E sills is adequate but not exceptional. Road salt penetrates through minor stone chips and sill drain holes, causing internal corrosion that is invisible until it breaks through.",
    fix: "1. Annual Waxoyl or Dinitrol cavity injection is the best prevention\n2. Treat visible surface rust immediately before it spreads\n3. Structural sill repairs require bodywork specialist\n4. Budget: £200-800 for structural sill repair depending on severity",
    severity: "moderate",
    mileage_start: 1, mileage_end: 999999,
    repair_cost_low: 200, repair_cost_high: 800,
    diy_difficulty: "hard",
    affected_years: "2014-2019",
    obd_codes: [],
    published: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // VAUXHALL ASTRA J 1.6 CDTi — 5 additional faults
  // ══════════════════════════════════════════════════════════════════════════
  {
    variant_id: v("astra-j-16-cdti"),
    title: "DPF Blockage and Regeneration System Failure",
    slug: "astra-j-cdti-dpf-blockage",
    summary: "DPF blockage is extremely common on the Astra J 1.6 CDTi. The engine's tendency to get stuck in failed regen cycles results in diesel contaminating the engine oil — a serious secondary issue.",
    symptoms: "- DPF warning light (amber)\n- Power reduction and restricted performance\n- Oil level above maximum (diesel in oil)\n- P2452/P2453 pressure differential codes\n- Black smoke from exhaust",
    cause: "The 1.6 CDTi's exhaust temperatures struggle to sustain regeneration in urban conditions. Failed active regens inject diesel into the exhaust late in the cycle — this diesel drains past the rings into the oil.",
    fix: "1. Urgent: check oil for diesel contamination before driving — change if contaminated\n2. Forced regen via Tech2 or compatible OBD tool\n3. If blocked beyond regen: professional clean £200-350\n4. Replacement DPF if internally damaged: £500-1,000\n5. Minimum fix: one 30-min motorway run per week going forward",
    severity: "severe",
    mileage_start: 40000, mileage_end: 90000,
    repair_cost_low: 200, repair_cost_high: 1000,
    diy_difficulty: "moderate",
    affected_years: "2012-2015",
    obd_codes: ["P2452", "P2453", "P246C"],
    published: true,
  },
  {
    variant_id: v("astra-j-16-cdti"),
    title: "EGR Cooler Failure and Intake Contamination",
    slug: "astra-j-cdti-egr-cooler-failure",
    summary: "EGR cooler failure on the Astra J 1.6 CDTi causes coolant loss and in severe cases, coolant enters the intake manifold. This is a more serious failure than a simple EGR valve block.",
    symptoms: "- Coolant level dropping without visible leak\n- White smoke with sweet smell\n- Rough running after extended idling\n- P0401 EGR flow fault\n- Coolant contamination in intake",
    cause: "The EGR cooler corrodes internally, causing its coolant passages to leak. Combined with the chronic EGR valve carbonising, both components often need to be addressed simultaneously.",
    fix: "1. Pressure test cooling system to confirm EGR cooler is the source\n2. Replace cooler and valve together — they are adjacent and labour overlaps\n3. Flush intake manifold before restarting\n4. OEM Pierburg or Valeo unit recommended\n5. Cost: £500-800 at indie diesel specialist",
    severity: "severe",
    mileage_start: 70000, mileage_end: 130000,
    repair_cost_low: 500, repair_cost_high: 800,
    diy_difficulty: "hard",
    affected_years: "2012-2015",
    obd_codes: ["P0401", "P0128"],
    published: true,
  },
  {
    variant_id: v("astra-j-16-cdti"),
    title: "Turbocharger Oil Feed Pipe Failure",
    slug: "astra-j-cdti-turbo-oil-pipe",
    summary: "The oil feed pipe to the turbocharger on the Astra J 1.6 CDTi can crack or block, starving the turbo of lubrication. This leads to premature bearing failure and expensive turbo replacement.",
    symptoms: "- Oil leak from turbo area (dripping on exhaust)\n- Blue smoke on startup\n- Turbo whine increasing in pitch\n- Loss of power over time\n- Oil consumption increasing",
    cause: "The banjo-bolt oil feed fitting at the top of the turbocharger can crack from vibration. Oil then leaks onto the hot exhaust manifold. Separately, sludge can block the feed pipe and starve the bearings.",
    fix: "1. Inspect oil feed banjo fitting and pipe for cracks or leaks\n2. Replace feed pipe if cracked — OEM or braided steel aftermarket\n3. If bearings already worn: turbo replacement (remanufactured £300-600)\n4. Always change oil and filter when replacing turbo\n5. Fitted: £500-900",
    severity: "severe",
    mileage_start: 80000, mileage_end: 150000,
    repair_cost_low: 500, repair_cost_high: 900,
    diy_difficulty: "hard",
    affected_years: "2012-2015",
    obd_codes: ["P0299"],
    published: true,
  },
  {
    variant_id: v("astra-j-16-cdti"),
    title: "Diesel Injector Seal Leaks",
    slug: "astra-j-cdti-injector-seals",
    summary: "Injector copper sealing washers on the Astra J 1.6 CDTi harden and allow combustion gases to bypass the injector seat. This causes carbonisation around the injector tops and eventually rough running.",
    symptoms: "- Diesel or combustion smell from engine bay\n- Black carbon deposits around injector tops\n- Rough idle at low temperature\n- Occasional misfire codes\n- Slight diesel weep visible",
    cause: "The copper crush washers that seal each injector against the cylinder head compress and deform permanently over many heat cycles. Once the seal loses clamping force, combustion gases and fuel bypass the seat.",
    fix: "1. Remove injectors and fit new copper crush washers (£2-5 each) and O-rings\n2. Clean injector bore with correct cleaning tool before refitting\n3. Re-torque to spec — over-tightening damages the head\n4. Full job: £150-300 at indie",
    severity: "moderate",
    mileage_start: 70000, mileage_end: 140000,
    repair_cost_low: 150, repair_cost_high: 300,
    diy_difficulty: "hard",
    affected_years: "2012-2015",
    obd_codes: [],
    published: true,
  },
  {
    variant_id: v("astra-j-16-cdti"),
    title: "Rear Axle Twist Beam Corrosion",
    slug: "astra-j-rear-axle-corrosion",
    summary: "The rear torsion beam axle on the Astra J corrodes in the UK climate. Surface rust progresses to structural corrosion on high-mileage or older examples, and is a common MOT advisory.",
    symptoms: "- Visible orange rust on rear axle beam\n- Squeaking from rear over bumps\n- MOT advisory or failure for corrosion\n- Rear handling feels vague",
    cause: "Unpainted or inadequately protected steel on the rear axle is attacked by road salt. The beam's box sections and trailing arms corrode from inside. High-mileage cars with no underbody treatment are worst affected.",
    fix: "1. Annual underseal or Waxoyl treatment is the best prevention\n2. Light surface rust: wire brush, rust converter, chassis paint\n3. Structural beam corrosion: replacement axle beam (salvage: £100-200, new: £400+)\n4. Always address before MOT rather than after failure",
    severity: "moderate",
    mileage_start: 1, mileage_end: 999999,
    repair_cost_low: 100, repair_cost_high: 600,
    diy_difficulty: "moderate",
    affected_years: "2009-2015",
    obd_codes: [],
    published: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // VAUXHALL ASTRA H 1.7 CDTi — 5 faults
  // ══════════════════════════════════════════════════════════════════════════
  {
    variant_id: v("astra-h-17-cdti"),
    title: "EGR Valve Failure",
    slug: "astra-h-cdti-egr-failure",
    summary: "The Isuzu-sourced Z17DTH and Z17DTJ engines in the Astra H have a well-documented EGR valve failure. Carbon deposits cause the valve to stick, resulting in power loss and increased emissions.",
    symptoms: "- EML warning light\n- Power loss between 1,500-2,500 RPM\n- Rough idle\n- Black or white smoke\n- P0400, P0401 or P1401 codes",
    cause: "Exhaust gas recirculation deposits carbon on the EGR valve seat and passages. Urban driving with frequent cold starts accelerates build-up. The 1.7 CDTi's EGR system is particularly prone to early fouling.",
    fix: "1. Remove and clean EGR valve — wire brush and carb cleaner\n2. Clean intake manifold passages\n3. Replacement EGR: £60-200 pattern, £250+ OEM\n4. Consider EGR blanking plate for a permanent solution\n5. Fitted: £150-350",
    severity: "moderate",
    mileage_start: 50000, mileage_end: 100000,
    repair_cost_low: 80, repair_cost_high: 350,
    diy_difficulty: "moderate",
    affected_years: "2004-2010",
    obd_codes: ["P0400", "P0401", "P1401"],
    published: true,
  },
  {
    variant_id: v("astra-h-17-cdti"),
    title: "DPF Blockage",
    slug: "astra-h-cdti-dpf-blockage",
    summary: "DPF-equipped Astra H 1.7 CDTi models (post-2007) suffer from the same DPF blockage issues as most diesel Vauxhalls of this era. Urban use is the root cause.",
    symptoms: "- DPF warning light illuminated\n- Reduced performance\n- P2452, P2453 codes\n- Excessive black smoke",
    cause: "Short cold trips in urban environments prevent the DPF from reaching regeneration temperature. The 1.7 CDTi's smaller displacement means it takes longer to generate sufficient exhaust heat.",
    fix: "1. Attempt passive regen with a 30-min motorway run\n2. Forced regen via diagnostic tool if passive fails\n3. Professional DPF clean: £200-300\n4. Replacement if physically damaged: £400-800",
    severity: "moderate",
    mileage_start: 40000, mileage_end: 90000,
    repair_cost_low: 200, repair_cost_high: 800,
    diy_difficulty: "moderate",
    affected_years: "2007-2010",
    obd_codes: ["P2452", "P2453"],
    published: true,
  },
  {
    variant_id: v("astra-h-17-cdti"),
    title: "Dual Mass Flywheel Failure",
    slug: "astra-h-cdti-dmf-failure",
    summary: "DMF wear on the Astra H 1.7 CDTi is a high-mileage inevitability. The flywheel's internal dampers lose effectiveness, causing vibration and judder that makes the car unpleasant to drive.",
    symptoms: "- Juddering on pull-away from standstill\n- Rattling at idle that disappears when clutch pedal is pressed\n- Vibration through gear lever\n- Clunking when changing gear",
    cause: "Internal spring dampers in the flywheel lose their effectiveness with mileage and the heavy vibration of a diesel engine. Towing and hill driving accelerate wear.",
    fix: "1. Always replace DMF and clutch together — never a new clutch on a worn DMF\n2. LuK or Sachs kits recommended\n3. Solid flywheel conversion is a cost-effective long-term solution\n4. Labour: 4-5 hours. Total: £650-1,000",
    severity: "moderate",
    mileage_start: 80000, mileage_end: 150000,
    repair_cost_low: 650, repair_cost_high: 1000,
    diy_difficulty: "professional_only",
    affected_years: "2004-2010",
    obd_codes: [],
    published: true,
  },
  {
    variant_id: v("astra-h-17-cdti"),
    title: "Injector Failure and Hard Starting",
    slug: "astra-h-cdti-injector-failure",
    summary: "Injector failure on the Z17DTH engine causes misfires, rough running and in advanced cases prevents starting. The solenoid-type injectors used in this engine respond well to professional cleaning.",
    symptoms: "- Rough idle and vibration\n- Hard cold starting\n- White smoke on startup\n- Loss of power at high RPM\n- P0201-P0204 codes",
    cause: "Solenoid injectors wear at their internal control valve and needle seat. Contaminated fuel or extended service intervals accelerate deterioration. Each injector has a calibration code.",
    fix: "1. Contribution test to identify failing cylinder\n2. Remove and send for ultrasonic cleaning and test — often restores function\n3. Replacement injectors must be coded to ECU\n4. Cost: £150-400 per injector fitted",
    severity: "severe",
    mileage_start: 90000, mileage_end: 160000,
    repair_cost_low: 250, repair_cost_high: 800,
    diy_difficulty: "professional_only",
    affected_years: "2004-2010",
    obd_codes: ["P0201", "P0202", "P0263"],
    published: true,
  },
  {
    variant_id: v("astra-h-17-cdti"),
    title: "Timing Belt Failure (Z17DTH)",
    slug: "astra-h-cdti-timing-belt",
    summary: "Unlike the later Astra J (which has a chain), the Astra H 1.7 CDTi (Z17DTH engine) uses a timing belt. Belt failure is catastrophic on this interference engine. The service interval is 60,000 miles or 4 years.",
    symptoms: "- No warning before failure\n- Engine stops abruptly when driving\n- Engine will not restart after failure\n- Bent valves, damaged pistons on failure",
    cause: "Rubber timing belts degrade with age and heat cycling. The Z17DTH's 60,000-mile or 4-year belt interval must be strictly observed. Many high-mileage examples have no documented belt history.",
    fix: "1. Replace belt, tensioner, idler and water pump as a complete kit at 60k/4 years\n2. If history unknown: replace immediately regardless of apparent mileage\n3. Use Gates or Dayco belt kit only — no cheap pattern parts on a timing belt\n4. Cost: £300-500 fitted",
    severity: "critical",
    mileage_start: 1, mileage_end: 60000,
    repair_cost_low: 300, repair_cost_high: 500,
    diy_difficulty: "hard",
    affected_years: "2004-2010",
    obd_codes: [],
    published: true,
  },

  ]; // end faults array
};

// ─── TAG MAP ────────────────────────────────────────────────────────────────
const TAG_MAP = {
  "fiesta-mk7-ecoboost-thermostat-failure":      ["cooling"],
  "fiesta-mk7-ecoboost-clutch-wear":             ["clutch"],
  "fiesta-mk7-ecoboost-eps-failure":             ["steering", "electrics"],
  "fiesta-mk7-rear-torsion-beam-corrosion":      ["rust", "suspension"],
  "fiesta-mk7-tdci-egr-failure":                 ["egr"],
  "fiesta-mk7-tdci-injector-failure":            ["injectors"],
  "fiesta-mk7-tdci-turbo-failure":               ["turbo"],
  "fiesta-mk7-tdci-glow-plug-failure":           ["engine"],
  "fiesta-mk7-tdci-dmf-judder":                  ["flywheel", "clutch"],
  "fiesta-mk6-timing-chain-rattle":              ["timing-chain", "engine"],
  "fiesta-mk6-sill-corrosion":                   ["rust"],
  "fiesta-mk6-clutch-wear":                      ["clutch"],
  "focus-mk2-tdci-dpf-blockage":                 ["dpf"],
  "focus-mk2-tdci-injector-seals":               ["injectors"],
  "focus-mk2-tdci-swirl-flap-motor":             ["swirl-flaps", "electrics"],
  "focus-mk3-ecoboost-timing-chain":             ["timing-chain", "engine"],
  "focus-mk3-ecoboost-coolant-loss":             ["cooling", "head-gasket"],
  "focus-mk3-ecoboost-boost-leak":               ["turbo"],
  "focus-mk3-ecoboost-water-pump":               ["cooling"],
  "focus-mk3-rear-axle-bush":                    ["suspension"],
  "focus-mk3-tdci-dpf-blockage":                 ["dpf"],
  "focus-mk3-tdci-egr-failure":                  ["egr", "cooling"],
  "focus-mk3-tdci-turbocharger-failure":         ["turbo"],
  "focus-mk3-tdci-dmf-failure":                  ["flywheel", "clutch"],
  "focus-mk3-tdci-injector-failure":             ["injectors"],
  "focus-mk3-tdci-glow-plug":                    ["engine"],
  "corsa-d-cdti-turbo-failure":                  ["turbo"],
  "corsa-d-cdti-fuel-pump-failure":              ["injectors", "engine"],
  "corsa-d-cdti-injector-failure":               ["injectors"],
  "corsa-d-cdti-glow-plug-failure":              ["engine"],
  "corsa-d-12-timing-chain-rattle":              ["timing-chain", "engine"],
  "corsa-d-12-wheel-bearing":                    ["wheel-bearing", "suspension"],
  "corsa-d-12-throttle-body":                    ["engine"],
  "corsa-d-12-power-steering-failure":           ["power-steering", "steering"],
  "corsa-e-14-timing-chain":                     ["timing-chain", "engine"],
  "corsa-e-14-coolant-loss":                     ["cooling", "head-gasket"],
  "corsa-e-14-throttle-body":                    ["engine"],
  "corsa-e-14-turbo-actuator":                   ["turbo"],
  "corsa-e-14-rear-sill-corrosion":              ["rust"],
  "astra-j-cdti-dpf-blockage":                   ["dpf"],
  "astra-j-cdti-egr-cooler-failure":             ["egr", "cooling"],
  "astra-j-cdti-turbo-oil-pipe":                 ["turbo"],
  "astra-j-cdti-injector-seals":                 ["injectors"],
  "astra-j-rear-axle-corrosion":                 ["rust", "suspension"],
  "astra-h-cdti-egr-failure":                    ["egr"],
  "astra-h-cdti-dpf-blockage":                   ["dpf"],
  "astra-h-cdti-dmf-failure":                    ["flywheel", "clutch"],
  "astra-h-cdti-injector-failure":               ["injectors"],
  "astra-h-cdti-timing-belt":                    ["timing-belt", "engine"],
};

// ─── MAIN ───────────────────────────────────────────────────────────────────
async function seed() {
  console.log("╔═══════════════════════════════════════════╗");
  console.log("║  CKF Phase 2a — Ford + Vauxhall Expansion ║");
  console.log("╚═══════════════════════════════════════════╝\n");

  const { data: variants, error: vErr } = await supabase.from("variants").select("id, slug");
  if (vErr) throw new Error(vErr.message);

  const { data: tags, error: tErr } = await supabase.from("tags").select("id, slug");
  if (tErr) throw new Error(tErr.message);

  process.stdout.write("Upserting faults…  ");
  const faultRows = FAULTS(variants);
  const faults = await upsert("faults", faultRows, "slug");
  console.log(`✓  ${faults.length} faults`);

  process.stdout.write("Linking tags…      ");
  const tagBySlug  = Object.fromEntries(tags.map(t => [t.slug, t.id]));
  const faultBySlug = Object.fromEntries(faults.map(f => [f.slug, f.id]));
  const ftRows = [];
  for (const [fs, ts] of Object.entries(TAG_MAP)) {
    const fid = faultBySlug[fs]; if (!fid) continue;
    for (const t of ts) { const tid = tagBySlug[t]; if (tid) ftRows.push({ fault_id: fid, tag_id: tid }); }
  }
  await upsertNoReturn("fault_tags", ftRows, "fault_id,tag_id");
  console.log(`✓  ${ftRows.length} links`);

  const { count } = await supabase.from("faults").select("*", { count: "exact", head: true }).eq("published", true);
  console.log(`\n✅  Done. Total published faults in DB: ${count}`);
}

seed().catch(e => { console.error("❌", e.message); process.exit(1); });
