/**
 * CKF Phase 3b — Audi A4/Q5 · Nissan Juke/Note · Peugeot 208/308 · Renault Megane/Scenic
 */
import { createClient } from "@supabase/supabase-js";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const ws = require("ws");

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
  { auth: { persistSession: false }, realtime: { transport: ws } }
);

const up = async (table, rows, conflict) => { const { data, error } = await sb.from(table).upsert(rows, { onConflict: conflict }).select(); if (error) throw new Error(`[${table}] ${error.message}`); return data; };
const ins = async (table, rows, conflict) => { const { error } = await sb.from(table).upsert(rows, { onConflict: conflict, ignoreDuplicates: true }); if (error) throw new Error(`[${table}] ${error.message}`); };
const get = (arr, slug) => { const r = arr.find(x => x.slug === slug); if (!r) throw new Error(`Missing: ${slug}`); return r; };

async function run() {
  console.log("Phase 3b — Audi · Nissan · Peugeot · Renault\n");

  const { data: models } = await sb.from("models").select("id, slug");
  const { data: tags }   = await sb.from("tags").select("id, slug");

  const variantRows = [
    // Audi A4
    { model_id: get(models,"a4").id, name: "B8 2.0 TDI 143bhp", slug: "a4-b8-20-tdi-143", engine: "2.0 TDI 143bhp CR", year_start: 2008, year_end: 2015, body_type: "Saloon", transmission: "Manual", fuel_type: "Diesel", description: "The B8 A4 TDI is a popular executive diesel with high fleet mileages. EGR, DPF and timing belt are the key maintenance watches." },
    // Audi Q5
    { model_id: get(models,"q5").id, name: "Mk1 2.0 TDI 170bhp", slug: "q5-mk1-20-tdi-170", engine: "2.0 TDI 170bhp CR", year_start: 2008, year_end: 2017, body_type: "SUV", transmission: "Automatic", fuel_type: "Diesel", description: "Audi's mid-size SUV. The Quattro drivetrain adds Haldex complexity; DPF and EGR issues are shared with the wider VAG TDI family." },
    // Nissan Juke
    { model_id: get(models,"juke").id, name: "Mk1 1.6 DIG-T 190bhp", slug: "juke-mk1-16-digt-190", engine: "1.6 DIG-T 190bhp", year_start: 2013, year_end: 2019, body_type: "SUV", transmission: "Manual", fuel_type: "Petrol", description: "The hot Juke NISMO. Turbo issues and CVT gearbox problems are the primary concerns." },
    { model_id: get(models,"juke").id, name: "Mk1 1.5 dCi 110bhp", slug: "juke-mk1-15-dci-110", engine: "1.5 dCi 110bhp K9K", year_start: 2010, year_end: 2019, body_type: "SUV", transmission: "Manual", fuel_type: "Diesel", description: "The frugal diesel Juke. The K9K engine's timing chain and DPF issues transfer directly from the Qashqai." },
    // Nissan Note
    { model_id: get(models,"note").id, name: "E11 1.5 dCi 90bhp", slug: "note-e11-15-dci-90", engine: "1.5 dCi 90bhp K9K", year_start: 2006, year_end: 2013, body_type: "MPV", transmission: "Manual", fuel_type: "Diesel", description: "A practical MPV diesel. Shares K9K engine with Qashqai and Clio — same timing chain and DPF concerns apply." },
    // Peugeot 208
    { model_id: get(models,"208").id, name: "Mk1 1.6 BlueHDi 100bhp", slug: "208-mk1-16-bluehdi", engine: "1.6 BlueHDi 100bhp", year_start: 2012, year_end: 2019, body_type: "Hatchback", transmission: "Manual", fuel_type: "Diesel", description: "PSA's updated HDi diesel. Still shares the 60,000-mile timing belt interval of its predecessor — a critical maintenance item many owners miss." },
    { model_id: get(models,"208").id, name: "Mk1 1.2 PureTech 82bhp", slug: "208-mk1-12-puretech", engine: "1.2 PureTech 82bhp", year_start: 2012, year_end: 2019, body_type: "Hatchback", transmission: "Manual", fuel_type: "Petrol", description: "The PureTech three-cylinder petrol is smooth but has a known timing belt issue — it uses a wet belt in oil that can fail prematurely." },
    // Peugeot 308
    { model_id: get(models,"308").id, name: "Mk1 1.6 HDi 112bhp", slug: "308-mk1-16-hdi-112", engine: "1.6 HDi 112bhp", year_start: 2007, year_end: 2013, body_type: "Hatchback", transmission: "Manual", fuel_type: "Diesel", description: "The 308 Mk1 HDi is well-regarded but the 60,000-mile timing belt interval catches many owners out. DPF issues in urban use are common." },
    // Renault Megane
    { model_id: get(models,"megane").id, name: "Mk3 1.5 dCi 110bhp", slug: "megane-mk3-15-dci-110", engine: "1.5 dCi 110bhp K9K", year_start: 2008, year_end: 2016, body_type: "Hatchback", transmission: "Manual", fuel_type: "Diesel", description: "The K9K 1.5 dCi Megane is a solid diesel but timing chain, injector return pipes and EDC clutch issues follow it from the Clio." },
    // Renault Scenic
    { model_id: get(models,"scenic").id, name: "Mk3 1.5 dCi 110bhp", slug: "scenic-mk3-15-dci-110", engine: "1.5 dCi 110bhp K9K", year_start: 2009, year_end: 2016, body_type: "MPV", transmission: "Manual", fuel_type: "Diesel", description: "The family MPV diesel. K9K engine faults (timing chain, injectors, DPF) are well-documented and transfer directly from the Megane." },
  ];

  const variants = await up("variants", variantRows, "model_id,slug");
  console.log(`Variants: ${variants.length}`);
  const vid = s => get(variants, s).id;

  const faultRows = [
    // ── Audi A4 B8 2.0 TDI ───────────────────────────────────────────────
    { variant_id: vid("a4-b8-20-tdi-143"), title: "Timing Belt Failure", slug: "a4-b8-timing-belt", summary: "The B8 A4 2.0 TDI uses a timing belt with a 140,000-mile service interval. Many specialists recommend 100,000 miles. Belt failure is catastrophic on this interference engine.", symptoms: "- No warning before failure\n- Engine stops suddenly\n- Will not restart\n- Catastrophic valve and piston damage", cause: "Rubber belt degradation with age, heat and mileage. The official Audi interval of 140k miles is widely considered too long by independent specialists.", fix: "1. Replace belt, tensioner, idler and water pump as a kit\n2. Recommend at 100,000 miles regardless of official interval\n3. Gates or Dayco kit only\n4. Cost: £400-700 fitted", severity: "critical", mileage_start: 100000, mileage_end: 140000, repair_cost_low: 400, repair_cost_high: 700, diy_difficulty: "hard", affected_years: "2008-2015", obd_codes: [], published: true },

    { variant_id: vid("a4-b8-20-tdi-143"), title: "EGR Cooler Failure and Coolant Loss", slug: "a4-b8-egr-cooler", summary: "EGR cooler failure is common on the B8 A4 TDI. Internal corrosion allows coolant to leak into the intake — initially causing rough running and white smoke.", symptoms: "- Coolant level dropping\n- White smoke with sweet smell\n- Rough running\n- P0401 EGR code", cause: "Coolant passages inside the EGR cooler corrode. Coolant enters the recirculated exhaust path and flows into the intake manifold.", fix: "1. Pressure test cooling system\n2. Replace EGR cooler and valve together\n3. Flush intake manifold\n4. OEM Audi/Pierburg part: £500-900 fitted", severity: "severe", mileage_start: 70000, mileage_end: 140000, repair_cost_low: 500, repair_cost_high: 900, diy_difficulty: "hard", affected_years: "2008-2015", obd_codes: ["P0401","P0128"], published: true },

    { variant_id: vid("a4-b8-20-tdi-143"), title: "DPF Blockage", slug: "a4-b8-dpf-blockage", summary: "The A4 B8 TDI is frequently used as a company car on short local journeys rather than motorway runs. DPF blockage is the most common ownership complaint.", symptoms: "- DPF warning light\n- Power loss\n- Oil above max (diesel contamination)\n- P2452/P2453 codes", cause: "Short trips prevent regeneration. The A4's larger displacement helps but urban use still accumulates soot faster than passive regen clears it.", fix: "1. Check oil for diesel dilution\n2. Force regen via VCDS\n3. Professional DPF clean: £200-350\n4. Replacement: £700-1,400", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 200, repair_cost_high: 1400, diy_difficulty: "moderate", affected_years: "2008-2015", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("a4-b8-20-tdi-143"), title: "Turbocharger Failure", slug: "a4-b8-turbo-failure", summary: "Turbocharger failure on the B8 A4 TDI mirrors the wider VAG TDI pattern — oil sludge in the feed pipe causes bearing failure, often presenting as a sudden loss of boost.", symptoms: "- Loud whining from turbo\n- Loss of power and boost\n- Blue smoke on acceleration\n- P0299 underboost", cause: "Oil sludge blocks the turbo oil feed. Long oil change intervals in company car use are the main contributing factor.", fix: "1. Check oil feed pipe\n2. Remanufactured unit: £400-700\n3. Flush oil system on installation\n4. Fitted: £650-1,100", severity: "severe", mileage_start: 100000, mileage_end: 180000, repair_cost_low: 650, repair_cost_high: 1100, diy_difficulty: "hard", affected_years: "2008-2015", obd_codes: ["P0299"], published: true },

    { variant_id: vid("a4-b8-20-tdi-143"), title: "Injector Failure", slug: "a4-b8-injector-failure", summary: "High-mileage A4 B8 TDIs suffer injector wear, causing rough running, smoke and diesel contamination of engine oil.", symptoms: "- Rough idle and misfires\n- Hard cold starting\n- White smoke on startup\n- Oil level rising\n- P0201-P0204 codes", cause: "Common rail injectors wear over high mileage. Extended service intervals and contaminated fuel accelerate degradation.", fix: "1. Contribution test identifies worst injector\n2. Ultrasonic clean and test before replacing\n3. New injectors coded to ECU\n4. Cost: £300-600 per injector fitted", severity: "severe", mileage_start: 100000, mileage_end: 200000, repair_cost_low: 350, repair_cost_high: 1200, diy_difficulty: "professional_only", affected_years: "2008-2015", obd_codes: ["P0201","P0202"], published: true },

    // ── Audi Q5 Mk1 2.0 TDI ──────────────────────────────────────────────
    { variant_id: vid("q5-mk1-20-tdi-170"), title: "DPF Blockage in Urban Use", slug: "q5-mk1-dpf-blockage", summary: "The Q5 TDI is a family SUV often used on the school run. The combination of heavy kerb weight and short trips causes chronic DPF blockage.", symptoms: "- DPF warning light\n- Power loss\n- Oil level rising\n- P2452/P2453 codes", cause: "The Q5's mass requires higher engine load in traffic, but exhaust temperatures remain too low for regeneration on short trips.", fix: "1. Check oil for diesel dilution\n2. Force regen via VCDS\n3. Professional DPF clean: £250-400\n4. Replacement: £800-1,500", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 250, repair_cost_high: 1500, diy_difficulty: "moderate", affected_years: "2008-2017", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("q5-mk1-20-tdi-170"), title: "Haldex Quattro Rear Differential Failure", slug: "q5-mk1-haldex-failure", summary: "The Q5 Quattro uses a Haldex rear differential that requires regular oil and filter changes. Neglected units lose rear drive, reducing the car to front-wheel drive in slippery conditions.", symptoms: "- Poor traction on wet or slippery roads\n- 4WD fault light\n- Rear wheels not receiving drive\n- Haldex warning on MMI screen", cause: "Haldex fluid breaks down without regular changes (every 40,000 miles). The clutch pack and pump wear, reducing the unit's ability to transfer drive to the rear axle.", fix: "1. Haldex fluid and filter service first: £100-200\n2. Pump replacement if worn: £400-700\n3. Full unit replacement: £1,000-2,000\n4. Always service on purchase if history unknown", severity: "severe", mileage_start: 60000, mileage_end: 150000, repair_cost_low: 100, repair_cost_high: 2000, diy_difficulty: "moderate", affected_years: "2008-2017", obd_codes: [], published: true },

    { variant_id: vid("q5-mk1-20-tdi-170"), title: "EGR and Timing Belt Failure", slug: "q5-mk1-egr-timing", summary: "The Q5 TDI shares the EGR cooler failure of the wider VAG TDI family, plus the timing belt must be replaced at 140,000 miles — a job many owners defer dangerously.", symptoms: "- Coolant loss (EGR cooler)\n- White smoke (EGR cooler)\n- P0401 EGR code\n- No warning for timing belt until it fails", cause: "EGR cooler corrodes internally; timing belt degrades with age. Both are high-consequence failures if ignored.", fix: "1. Replace EGR cooler and valve together\n2. Replace timing belt at 100,000 miles (not 140k)\n3. Include water pump, tensioner and idler in belt service\n4. Combined cost: £900-1,500", severity: "critical", mileage_start: 80000, mileage_end: 140000, repair_cost_low: 500, repair_cost_high: 1500, diy_difficulty: "hard", affected_years: "2008-2017", obd_codes: ["P0401"], published: true },

    { variant_id: vid("q5-mk1-20-tdi-170"), title: "Air Suspension Compressor Failure", slug: "q5-mk1-air-suspension", summary: "Q5s fitted with the optional air suspension develop compressor failures and air bag leaks. The car visibly sags and a warning appears. Repair costs are significant.", symptoms: "- Car sitting lower than normal\n- Air suspension warning light\n- Compressor running continuously\n- Bouncy or vague ride\n- P139F or C10A2 fault codes", cause: "The air compressor wears out from continuous use trying to compensate for leaking air bags or lines. Air bags perish with age in the UK climate.", fix: "1. Identify leak source first — compressor or bag\n2. Air bag replacement: £200-400 per corner\n3. Compressor replacement: £300-600\n4. Consider conversion to standard coilover suspension: £600-900", severity: "severe", mileage_start: 80000, mileage_end: 160000, repair_cost_low: 300, repair_cost_high: 1500, diy_difficulty: "professional_only", affected_years: "2008-2017", obd_codes: ["P139F"], published: true },

    // ── Nissan Juke Mk1 1.6 DIG-T ────────────────────────────────────────
    { variant_id: vid("juke-mk1-16-digt-190"), title: "Turbocharger Failure", slug: "juke-digt-turbo-failure", summary: "The turbocharged 1.6 DIG-T Juke is fun but the turbo is stressed by the engine's high output. Turbo failures from oil starvation and bearing wear are a known issue.", symptoms: "- Loud whine from engine bay\n- Loss of boost and power\n- Blue smoke on acceleration\n- P0299 underboost", cause: "The high-output DIG-T places extreme demand on the turbocharger. Oil sludge from infrequent changes blocks the feed, starving the bearings.", fix: "1. Verify oil feed pipe is clear\n2. Remanufactured turbo: £400-700\n3. Flush oil on install — old oil will kill new turbo\n4. Fitted: £650-1,000", severity: "severe", mileage_start: 60000, mileage_end: 120000, repair_cost_low: 650, repair_cost_high: 1000, diy_difficulty: "hard", affected_years: "2013-2019", obd_codes: ["P0299"], published: true },

    { variant_id: vid("juke-mk1-16-digt-190"), title: "CVT Gearbox Failure and Shudder", slug: "juke-digt-cvt-failure", summary: "The CVT automatic gearbox on the Juke DIG-T is known for shudder and failure. Fluid degradation is the root cause — the CVT fluid must be changed every 30,000 miles.", symptoms: "- Shudder or vibration under acceleration\n- Juddering when pulling away\n- Slipping or hesitation\n- Whining from gearbox\n- CVT warning light", cause: "CVT fluid breaks down with heat and age. The steel belt/chain and pulleys wear when run on degraded fluid. Nissan initially listed CVT fluid as 'lifetime' — which it is not.", fix: "1. CVT fluid change first (£150-200) — often resolves shudder if caught early\n2. CVT relearn procedure after fluid change\n3. Full CVT replacement if internally damaged: £2,000-4,000\n4. Avoid this gearbox for towing or spirited driving", severity: "severe", mileage_start: 60000, mileage_end: 130000, repair_cost_low: 150, repair_cost_high: 4000, diy_difficulty: "professional_only", affected_years: "2013-2019", obd_codes: [], published: true },

    { variant_id: vid("juke-mk1-16-digt-190"), title: "Intercooler Boost Pipe Failure", slug: "juke-digt-boost-pipe", summary: "The boost pipes and intercooler connections on the DIG-T Juke are prone to splitting under sustained boost pressure, causing a noticeable flat spot.", symptoms: "- Flat spot under hard acceleration\n- Hissing or whooshing under boost\n- P0299 underboost code\n- Loss of power at high RPM", cause: "The plastic boost pipes and rubber connections deteriorate with heat and age. The high turbo pressures on the performance variant stress the plumbing more than standard variants.", fix: "1. Feel along all boost pipes with engine running for air leaks\n2. Common split points: throttle body elbow, intercooler outlet\n3. Silicone hose upgrade kits: £40-100 (more durable than OEM)\n4. Easy DIY fix", severity: "moderate", mileage_start: 40000, mileage_end: 100000, repair_cost_low: 40, repair_cost_high: 200, diy_difficulty: "easy", affected_years: "2013-2019", obd_codes: ["P0299"], published: true },

    // ── Nissan Juke Mk1 1.5 dCi ──────────────────────────────────────────
    { variant_id: vid("juke-mk1-15-dci-110"), title: "Timing Chain Failure (K9K Engine)", slug: "juke-dci-timing-chain", summary: "The K9K 1.5 dCi engine's timing chain issue transfers directly from the Qashqai to the Juke. Chain rattle on cold start must be addressed immediately.", symptoms: "- Rattling on cold start\n- EML with P0016/P0017\n- Engine roughness when cold\n- In failure: engine stops suddenly", cause: "Same K9K chain tensioner wear as in Qashqai and Clio. Infrequent oil changes dramatically accelerate wear.", fix: "1. Full timing chain kit replacement at first sign of rattle\n2. 5W-40 synthetic oil, max 6,000-mile intervals\n3. Cost: £600-1,000 fitted", severity: "severe", mileage_start: 80000, mileage_end: 140000, repair_cost_low: 600, repair_cost_high: 1000, diy_difficulty: "hard", affected_years: "2010-2019", obd_codes: ["P0016","P0017"], published: true },

    { variant_id: vid("juke-mk1-15-dci-110"), title: "DPF Blockage", slug: "juke-dci-dpf-blockage", summary: "The Juke dCi is frequently used for urban journeys, causing chronic DPF blockage. The problem is especially common on lower-spec 86bhp variants.", symptoms: "- DPF warning light\n- Power reduction\n- Oil above max\n- P2452/P2453 codes", cause: "Short cold trips in the Juke dCi prevent adequate DPF regeneration temperatures. The K9K's small displacement means low exhaust heat in traffic.", fix: "1. Check oil for diesel dilution\n2. Force regen or professional clean\n3. Prevention: 30-min motorway run per week minimum", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 200, repair_cost_high: 900, diy_difficulty: "moderate", affected_years: "2010-2019", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("juke-mk1-15-dci-110"), title: "Injector Return Pipe Failure", slug: "juke-dci-injector-return-pipe", summary: "The K9K injector fuel return pipe clips crack and leak diesel. It is a fire risk if left unaddressed and affects all K9K-engined vehicles including the Juke.", symptoms: "- Strong diesel smell after running\n- Fuel staining around injectors\n- Hard starting when hot\n- Lumpy running under light loads", cause: "The plastic clip-on fuel return connections on the injectors become brittle with heat cycling. They develop hairline cracks that worsen progressively.", fix: "1. Inspect all return pipe clips — replace the complete set at once\n2. Repair kit available from £30\n3. Straightforward DIY job: 1-2 hours\n4. Do not delay — this is a fire risk", severity: "severe", mileage_start: 60000, mileage_end: 130000, repair_cost_low: 30, repair_cost_high: 150, diy_difficulty: "easy", affected_years: "2010-2019", obd_codes: ["P0087"], published: true },

    // ── Nissan Note E11 1.5 dCi ──────────────────────────────────────────
    { variant_id: vid("note-e11-15-dci-90"), title: "Timing Chain Failure (K9K)", slug: "note-dci-timing-chain", summary: "The Note E11 uses the same K9K 1.5 dCi as the Qashqai, Juke and Clio. The timing chain tensioner wear is identical — rattle must not be ignored.", symptoms: "- Cold-start chain rattle\n- P0016/P0017\n- Rough running when cold", cause: "K9K hydraulic tensioner wears with age and mileage. Infrequent oil changes are the leading cause.", fix: "1. Replace full chain kit at first rattle\n2. Strict 6,000-mile oil intervals going forward\n3. Cost: £500-900 fitted", severity: "severe", mileage_start: 80000, mileage_end: 140000, repair_cost_low: 500, repair_cost_high: 900, diy_difficulty: "hard", affected_years: "2006-2013", obd_codes: ["P0016","P0017"], published: true },

    { variant_id: vid("note-e11-15-dci-90"), title: "DPF Blockage", slug: "note-dci-dpf-blockage", summary: "The Note is frequently used as a family runabout on short trips — the worst use case for a diesel with a DPF. Blockage is the most common fault on diesel Notes.", symptoms: "- DPF warning light\n- Power loss\n- P2452/P2453 codes", cause: "Short family trips in the Note dCi prevent DPF regeneration. The MPV body style encourages low-speed, stop-start use.", fix: "1. Force regen or professional DPF clean\n2. Minimum 30-min motorway run per week\n3. Seriously consider a petrol Note instead", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 150, repair_cost_high: 800, diy_difficulty: "moderate", affected_years: "2006-2013", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("note-e11-15-dci-90"), title: "EGR Valve Failure", slug: "note-dci-egr-failure", summary: "EGR failure on the Note dCi produces power loss and rough running. The small engine is sensitive to any reduction in airflow caused by EGR carbon build-up.", symptoms: "- EML and power loss\n- Rough idle\n- P0400/P0401 codes", cause: "Carbon deposits restrict the EGR valve. Urban use accelerates the build-up.", fix: "1. Remove and clean EGR valve\n2. Clean intake passages\n3. Replacement if seized: £100-250\n4. Fitted: £200-400", severity: "moderate", mileage_start: 50000, mileage_end: 100000, repair_cost_low: 100, repair_cost_high: 400, diy_difficulty: "moderate", affected_years: "2006-2013", obd_codes: ["P0400","P0401"], published: true },

    // ── Peugeot 208 1.6 BlueHDi ──────────────────────────────────────────
    { variant_id: vid("208-mk1-16-bluehdi"), title: "Timing Belt Failure (60,000-Mile Interval)", slug: "peugeot-208-bluehdi-timing-belt", summary: "The 1.6 BlueHDi carries forward the PSA 60,000-mile timing belt interval from the 207. Many 208 owners are unaware — belt failure destroys the engine.", symptoms: "- No warning before failure\n- Engine stops suddenly while driving\n- Engine will not restart\n- Bent valves and damaged pistons", cause: "Rubber belt degradation at the strict 60k/4yr interval. PSA's short interval compensates for a design that places high stress on the belt.", fix: "1. Replace belt, tensioner, idler and water pump as a kit at 60k/4yr\n2. If history unknown: replace immediately\n3. Gates or Dayco kit only\n4. Cost: £300-550 fitted", severity: "critical", mileage_start: 1, mileage_end: 60000, repair_cost_low: 300, repair_cost_high: 550, diy_difficulty: "hard", affected_years: "2012-2019", obd_codes: [], published: true },

    { variant_id: vid("208-mk1-16-bluehdi"), title: "DPF Blockage", slug: "peugeot-208-bluehdi-dpf", summary: "Urban 208 BlueHDi drivers regularly face DPF blockage warnings. The small diesel is not suited to short city trips.", symptoms: "- DPF warning light\n- Power reduction\n- P2452/P2453 codes", cause: "Short trips prevent the DPF reaching regen temperature. The BlueHDi's AdBlue SCR system adds a second potential failure point.", fix: "1. 30-min motorway run\n2. Force regen via diagnostic tool\n3. Professional DPF clean: £200-350\n4. Replacement: £500-1,000", severity: "moderate", mileage_start: 30000, mileage_end: 70000, repair_cost_low: 200, repair_cost_high: 1000, diy_difficulty: "moderate", affected_years: "2012-2019", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("208-mk1-16-bluehdi"), title: "EGR Valve Carbon Build-Up", slug: "peugeot-208-bluehdi-egr", summary: "EGR failure on the 208 BlueHDi follows the established PSA pattern — carbon deposits restrict the valve, causing power loss and rough running.", symptoms: "- EML and power loss\n- Rough idle\n- Increased fuel consumption\n- P0400/P0401 codes", cause: "Carbon from recirculated exhaust gas coats the EGR valve. The city-friendly 208 is often used in the exact conditions that accelerate EGR fouling.", fix: "1. Remove and clean EGR valve\n2. Clean intake manifold\n3. Replacement EGR: £100-250\n4. Fitted: £250-450", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 100, repair_cost_high: 450, diy_difficulty: "moderate", affected_years: "2012-2019", obd_codes: ["P0400","P0401"], published: true },

    // ── Peugeot 208 1.2 PureTech ─────────────────────────────────────────
    { variant_id: vid("208-mk1-12-puretech"), title: "Timing Belt in Oil Failure (Wet Belt)", slug: "peugeot-208-puretech-wet-belt", summary: "The 1.2 PureTech engine uses a 'wet belt' timing system — the belt runs in engine oil. This reduces noise but the belt degrades faster than a conventional dry belt. PSA extended the replacement interval, but early failures occurred.", symptoms: "- No warning before failure\n- Engine stops suddenly\n- Engine will not restart\n- Catastrophic internal damage on failure\n- P0016/P0017 if belt slips rather than snaps", cause: "The wet belt degrades faster when oil is contaminated or at incorrect level. PSA revised the service interval but early 2012-2016 engines have experienced premature failures.", fix: "1. Replace wet belt kit at 60,000 miles or 5 years — do not extend\n2. Ensure correct oil specification (PSA B71 2312) is used — incorrect oil destroys the belt\n3. Cost: £350-600 fitted\n4. This is the single most important maintenance item on the PureTech", severity: "critical", mileage_start: 40000, mileage_end: 80000, repair_cost_low: 350, repair_cost_high: 600, diy_difficulty: "hard", affected_years: "2012-2019", obd_codes: ["P0016","P0017"], published: true },

    { variant_id: vid("208-mk1-12-puretech"), title: "Oil Consumption and Piston Ring Wear", slug: "peugeot-208-puretech-oil-consumption", summary: "The PureTech 1.2 engine has a documented issue with excessive oil consumption on early units. PSA introduced a revised piston ring specification to address the problem.", symptoms: "- Oil level dropping between services\n- Blue smoke on startup or overrun\n- Need to top up oil every 1,000-2,000 miles\n- Oil warning light on high-mileage examples", cause: "Early PureTech engines have piston rings that allow oil to enter the combustion chamber. PSA acknowledged the issue and revised the rings in later production.", fix: "1. Check if engine is within the affected build date range\n2. PSA issued a revised piston ring specification — some engines repaired under warranty\n3. Use correct PSA B71 5W-30 fully synthetic oil\n4. Engine rebuild or replacement if excessive: £2,000-4,000", severity: "severe", mileage_start: 30000, mileage_end: 100000, repair_cost_low: 200, repair_cost_high: 4000, diy_difficulty: "professional_only", affected_years: "2012-2016", obd_codes: [], published: true },

    // ── Peugeot 308 Mk1 1.6 HDi ──────────────────────────────────────────
    { variant_id: vid("308-mk1-16-hdi-112"), title: "Timing Belt Failure (60,000-Mile Interval)", slug: "peugeot-308-hdi-timing-belt", summary: "The 308 Mk1 1.6 HDi carries the same strict 60,000-mile belt interval as the 207. Many 308 owners are misled by the larger car into assuming a longer belt life.", symptoms: "- No warning before failure\n- Sudden engine stop\n- Will not restart\n- Catastrophic engine damage on failure", cause: "The PSA 1.6 HDi belt interval is strictly 60k/4yr. The 308's engine bay generates similar heat to the 207 — the belt condition does not improve with engine size.", fix: "1. Replace belt, tensioner, idler and water pump at 60k/4yr\n2. Use only Gates or Dayco belt kits\n3. Cost: £350-600 fitted\n4. Check history on any used purchase — many sellers are unaware of this interval", severity: "critical", mileage_start: 1, mileage_end: 60000, repair_cost_low: 350, repair_cost_high: 600, diy_difficulty: "hard", affected_years: "2007-2013", obd_codes: [], published: true },

    { variant_id: vid("308-mk1-16-hdi-112"), title: "EGR Valve Failure", slug: "peugeot-308-hdi-egr", summary: "EGR failure on the 308 HDi causes the familiar symptoms of power loss and rough running. The PSA 1.6 HDi EGR system is well-known for carbon build-up.", symptoms: "- EML and power loss\n- Rough idle\n- Black smoke\n- P0400/P0401 codes", cause: "Carbon deposits from exhaust gas recirculation accumulate on the EGR valve. More severe in urban use.", fix: "1. Remove and clean EGR valve thoroughly\n2. Clean intake manifold\n3. Replacement if valve is stuck: £120-280\n4. Fitted: £250-450", severity: "moderate", mileage_start: 50000, mileage_end: 100000, repair_cost_low: 100, repair_cost_high: 450, diy_difficulty: "moderate", affected_years: "2007-2013", obd_codes: ["P0400","P0401"], published: true },

    { variant_id: vid("308-mk1-16-hdi-112"), title: "DPF Blockage", slug: "peugeot-308-hdi-dpf", summary: "DPF blockage on the 308 HDi is a common complaint. Used as a family hatchback on short local journeys, many 308 diesels never get the sustained high-speed running needed for regeneration.", symptoms: "- DPF warning light\n- Power loss and limp mode\n- P2452/P2453 codes\n- Black smoke", cause: "Short family journeys prevent the DPF from reaching regeneration temperature. The larger 308 body means more weight and more fuel burned but still insufficient exhaust temperature in traffic.", fix: "1. 30-min motorway run at 2,500+ RPM\n2. Force regen via Peugeot Planet or generic EOBD tool\n3. Professional DPF clean: £200-350\n4. Replacement: £500-1,000", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 200, repair_cost_high: 1000, diy_difficulty: "moderate", affected_years: "2007-2013", obd_codes: ["P2452","P2453"], published: true },

    // ── Renault Megane Mk3 1.5 dCi ────────────────────────────────────────
    { variant_id: vid("megane-mk3-15-dci-110"), title: "Timing Chain Failure (K9K)", slug: "megane-mk3-dci-timing-chain", summary: "The K9K 1.5 dCi timing chain issue affects the Megane Mk3 just as it does the Clio, Juke and Qashqai. Chain rattle on cold start is a sign of imminent failure.", symptoms: "- Cold-start chain rattle\n- P0016/P0017 timing codes\n- Engine roughness when cold\n- In failure: engine stops suddenly", cause: "The K9K hydraulic tensioner wears with mileage. Extended oil change intervals dramatically accelerate chain wear.", fix: "1. Full chain kit at first rattle — do not delay\n2. 5W-40 fully synthetic, max 6,000-mile oil changes\n3. Cost: £600-1,000 fitted", severity: "severe", mileage_start: 80000, mileage_end: 150000, repair_cost_low: 600, repair_cost_high: 1000, diy_difficulty: "hard", affected_years: "2008-2016", obd_codes: ["P0016","P0017"], published: true },

    { variant_id: vid("megane-mk3-15-dci-110"), title: "Injector Return Pipe Failure", slug: "megane-mk3-dci-return-pipe", summary: "The K9K injector fuel return pipe clips crack with age — a fire risk found on all K9K-powered Renaults including the Megane. The repair is inexpensive but urgent.", symptoms: "- Strong diesel smell from engine bay\n- Fuel staining around injectors\n- Hot starting difficulty\n- Lumpy running", cause: "Plastic return pipe clips become brittle from heat cycling and develop cracks. The return fuel is hot diesel — the leak is a genuine fire risk.", fix: "1. Replace complete return pipe kit at once (£30-60)\n2. Simple DIY job: 1-2 hours\n3. Do not ignore — fire risk", severity: "severe", mileage_start: 60000, mileage_end: 130000, repair_cost_low: 30, repair_cost_high: 150, diy_difficulty: "easy", affected_years: "2008-2016", obd_codes: ["P0087"], published: true },

    { variant_id: vid("megane-mk3-15-dci-110"), title: "DPF Blockage", slug: "megane-mk3-dci-dpf", summary: "DPF blockage on the Megane Mk3 dCi is a familiar complaint. Urban family use prevents the regeneration cycle from completing.", symptoms: "- DPF warning light\n- Power loss\n- Oil level rising\n- P2452/P2453 codes", cause: "Short journeys in traffic prevent DPF regeneration. The Megane is often used as a secondary family car for local errands — the wrong application for a diesel.", fix: "1. Check oil for diesel dilution\n2. Force regen or professional clean\n3. 30-min motorway run per week preventatively", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 200, repair_cost_high: 900, diy_difficulty: "moderate", affected_years: "2008-2016", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("megane-mk3-15-dci-110"), title: "EGR Valve Carbon Blockage", slug: "megane-mk3-dci-egr", summary: "EGR valve carbon build-up on the Megane Mk3 dCi restricts airflow and causes power loss. It is one of the most frequently reported faults by Megane diesel owners.", symptoms: "- EML and reduced power\n- Rough idle and hesitation\n- Black smoke under load\n- P0400/P0401 codes", cause: "Carbon from recirculated exhaust gas coats the EGR valve assembly. Urban use and short trips accelerate the fouling process.", fix: "1. Remove and clean EGR valve\n2. Clean intake manifold passages\n3. Replacement if valve is beyond cleaning: £100-250\n4. Full job: £200-400", severity: "moderate", mileage_start: 50000, mileage_end: 100000, repair_cost_low: 100, repair_cost_high: 400, diy_difficulty: "moderate", affected_years: "2008-2016", obd_codes: ["P0400","P0401"], published: true },

    // ── Renault Scenic Mk3 1.5 dCi ───────────────────────────────────────
    { variant_id: vid("scenic-mk3-15-dci-110"), title: "Timing Chain Failure (K9K)", slug: "scenic-mk3-dci-timing-chain", summary: "The K9K timing chain issue is widespread across the Renault range and the Scenic Mk3 is no exception. Chain wear leads to rattling and ultimately engine failure.", symptoms: "- Cold-start chain rattle from engine\n- P0016/P0017 timing codes\n- Rough running when cold", cause: "K9K hydraulic tensioner wear. The Scenic's family MPV use often means short urban journeys that accelerate oil degradation.", fix: "1. Full timing chain kit replacement at first sign\n2. 5W-40 fully synthetic oil, 6,000-mile maximum interval\n3. Cost: £600-1,000 fitted", severity: "severe", mileage_start: 80000, mileage_end: 150000, repair_cost_low: 600, repair_cost_high: 1000, diy_difficulty: "hard", affected_years: "2009-2016", obd_codes: ["P0016","P0017"], published: true },

    { variant_id: vid("scenic-mk3-15-dci-110"), title: "DPF Blockage from Family Use", slug: "scenic-mk3-dci-dpf", summary: "The Scenic Mk3 dCi is the family diesel MPV — used for exactly the kind of short school-run trips that block DPFs. It is by far the most common fault reported by Scenic owners.", symptoms: "- DPF warning light\n- Power loss\n- Oil level rising\n- P2452/P2453 codes", cause: "School runs, supermarket trips and local errands are the core use case of an MPV — all of them too short for DPF regeneration.", fix: "1. Check oil for diesel contamination immediately\n2. Force regen via EOBD tool\n3. Professional DPF clean: £200-350\n4. Strongly consider a petrol Scenic for urban-only use", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 200, repair_cost_high: 900, diy_difficulty: "moderate", affected_years: "2009-2016", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("scenic-mk3-15-dci-110"), title: "Electric Sliding Door Motor Failure", slug: "scenic-mk3-sliding-door-motor", summary: "The Scenic Mk3's powered sliding rear doors develop motor faults, leaving the door either stuck open or requiring manual operation. A unique fault to the MPV body style.", symptoms: "- Sliding door won't open or close electrically\n- Door moves slowly then stops\n- Warning message on dashboard\n- Door rattles when driving", cause: "The electric sliding door motor wears with repeated use. The track mechanism also accumulates dirt and debris, increasing the load on the motor and accelerating wear.", fix: "1. Clean the door tracks thoroughly — often resolves slow-door issue\n2. Check motor brushes and electrical connections\n3. Replacement motor: £150-300\n4. Full door mechanism overhaul: £300-600", severity: "minor", mileage_start: 60000, mileage_end: 140000, repair_cost_low: 150, repair_cost_high: 600, diy_difficulty: "moderate", affected_years: "2009-2016", obd_codes: [], published: true },

    { variant_id: vid("scenic-mk3-15-dci-110"), title: "EGR Valve Carbon Blockage", slug: "scenic-mk3-dci-egr", summary: "EGR failure on the Scenic Mk3 follows the K9K pattern — carbon accumulation causes power loss and rough running, compounded by the MPV's urban use profile.", symptoms: "- EML and power loss\n- Rough idle\n- Black smoke\n- P0400/P0401 codes", cause: "Carbon deposits from exhaust gas recirculation block the EGR valve. Family MPV urban use creates ideal conditions for rapid fouling.", fix: "1. Remove and clean EGR valve\n2. Clean intake manifold passages\n3. Replacement if stuck: £100-250\n4. Total: £200-400", severity: "moderate", mileage_start: 50000, mileage_end: 100000, repair_cost_low: 100, repair_cost_high: 400, diy_difficulty: "moderate", affected_years: "2009-2016", obd_codes: ["P0400","P0401"], published: true },
  ];

  const insertedFaults = await up("faults", faultRows, "slug");
  console.log(`Faults: ${insertedFaults.length}`);

  const tagMap = {
    "a4-b8-timing-belt":            ["timing-belt","engine"],
    "a4-b8-egr-cooler":             ["egr","cooling"],
    "a4-b8-dpf-blockage":           ["dpf"],
    "a4-b8-turbo-failure":          ["turbo"],
    "a4-b8-injector-failure":       ["injectors"],
    "q5-mk1-dpf-blockage":          ["dpf"],
    "q5-mk1-haldex-failure":        ["gearbox"],
    "q5-mk1-egr-timing":            ["egr","timing-belt","cooling"],
    "q5-mk1-air-suspension":        ["suspension"],
    "juke-digt-turbo-failure":      ["turbo"],
    "juke-digt-cvt-failure":        ["gearbox"],
    "juke-digt-boost-pipe":         ["turbo"],
    "juke-dci-timing-chain":        ["timing-chain","engine"],
    "juke-dci-dpf-blockage":        ["dpf"],
    "juke-dci-injector-return-pipe":["injectors"],
    "note-dci-timing-chain":        ["timing-chain","engine"],
    "note-dci-dpf-blockage":        ["dpf"],
    "note-dci-egr-failure":         ["egr"],
    "peugeot-208-bluehdi-timing-belt":["timing-belt","engine"],
    "peugeot-208-bluehdi-dpf":      ["dpf"],
    "peugeot-208-bluehdi-egr":      ["egr"],
    "peugeot-208-puretech-wet-belt":["timing-belt","engine"],
    "peugeot-208-puretech-oil-consumption":["engine"],
    "peugeot-308-hdi-timing-belt":  ["timing-belt","engine"],
    "peugeot-308-hdi-egr":          ["egr"],
    "peugeot-308-hdi-dpf":          ["dpf"],
    "megane-mk3-dci-timing-chain":  ["timing-chain","engine"],
    "megane-mk3-dci-return-pipe":   ["injectors"],
    "megane-mk3-dci-dpf":           ["dpf"],
    "megane-mk3-dci-egr":           ["egr"],
    "scenic-mk3-dci-timing-chain":  ["timing-chain","engine"],
    "scenic-mk3-dci-dpf":           ["dpf"],
    "scenic-mk3-sliding-door-motor":["electrics"],
    "scenic-mk3-dci-egr":           ["egr"],
  };

  const tagBySlug   = Object.fromEntries(tags.map(t => [t.slug, t.id]));
  const faultBySlug = Object.fromEntries(insertedFaults.map(f => [f.slug, f.id]));
  const ftRows = [];
  for (const [fs, ts] of Object.entries(tagMap)) {
    const fid = faultBySlug[fs]; if (!fid) continue;
    for (const t of ts) { const tid = tagBySlug[t]; if (tid) ftRows.push({ fault_id: fid, tag_id: tid }); }
  }
  await ins("fault_tags", ftRows, "fault_id,tag_id");
  console.log(`Tag links: ${ftRows.length}`);

  const { count } = await sb.from("faults").select("*", { count: "exact", head: true }).eq("published", true);
  console.log(`\nTotal published faults: ${count}`);
}

run().catch(e => { console.error("Error:", e.message); process.exit(1); });
