/**
 * CKF Phase 3a — Zero-fault model expansion
 * Batch 1: Ford (Transit, Kuga, Mondeo) · VW (Polo, Passat, Tiguan) · BMW 5 Series
 */
import { createClient } from "@supabase/supabase-js";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const ws = require("ws");

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY,
  { auth: { persistSession: false }, realtime: { transport: ws } }
);

async function upsert(table, rows, conflict) {
  const { data, error } = await sb.from(table).upsert(rows, { onConflict: conflict }).select();
  if (error) throw new Error(`[${table}] ${error.message}`);
  return data;
}
async function noReturn(table, rows, conflict) {
  const { error } = await sb.from(table).upsert(rows, { onConflict: conflict, ignoreDuplicates: true });
  if (error) throw new Error(`[${table}] ${error.message}`);
}
const find = (arr, slug) => { const r = arr.find(x => x.slug === slug); if (!r) throw new Error(`Missing: ${slug}`); return r; };

async function run() {
  console.log("Phase 3a — Ford · VW · BMW 5 Series\n");

  // Pull existing makes + models
  const { data: makes }  = await sb.from("makes").select("id, slug");
  const { data: models } = await sb.from("models").select("id, slug, make_id");
  const { data: tags }   = await sb.from("tags").select("id, slug");
  const tagId = slug => find(tags, slug).id;

  const fordId  = find(makes, "ford").id;
  const vwId    = find(makes, "volkswagen").id;
  const bmwId   = find(makes, "bmw").id;

  // ── Variants ──────────────────────────────────────────────────────────────
  const variantRows = [
    // Ford Transit Custom
    { model_id: find(models,"transit").id, name: "Transit Custom 2.0 TDCi 130bhp", slug: "transit-custom-20-tdci", engine: "2.0 TDCi 130bhp", year_start: 2013, year_end: null, body_type: "Van", transmission: "Manual", fuel_type: "Diesel", description: "The UK's best-selling van. The 2.0 TDCi is a workhorse but DPF and EGR issues from urban use are endemic in fleet vehicles." },
    // Ford Kuga
    { model_id: find(models,"kuga").id, name: "Mk2 2.0 TDCi 150bhp", slug: "kuga-mk2-20-tdci", engine: "2.0 TDCi 150bhp", year_start: 2012, year_end: 2019, body_type: "SUV", transmission: "Manual", fuel_type: "Diesel", description: "Ford's mid-size SUV. Shares many components with the Focus Mk3, including its DPF and EGR weaknesses." },
    // Ford Mondeo
    { model_id: find(models,"mondeo").id, name: "Mk4 2.0 TDCi 140bhp", slug: "mondeo-mk4-20-tdci", engine: "2.0 TDCi 140bhp", year_start: 2007, year_end: 2014, body_type: "Saloon", transmission: "Manual", fuel_type: "Diesel", description: "The Mondeo Mk4 diesel is a solid rep car with high mileages. DMF and DPF issues dominate the ownership experience." },
    // VW Polo
    { model_id: find(models,"polo").id, name: "Mk5 1.2 TDI 75bhp", slug: "polo-mk5-12-tdi", engine: "1.2 TDI 75bhp", year_start: 2009, year_end: 2014, body_type: "Hatchback", transmission: "Manual", fuel_type: "Diesel", description: "The frugal Polo diesel. Timing belt failure and EGR issues are the most reported problems." },
    { model_id: find(models,"polo").id, name: "Mk5 1.4 85bhp", slug: "polo-mk5-14-85", engine: "1.4 85bhp", year_start: 2009, year_end: 2017, body_type: "Hatchback", transmission: "Manual", fuel_type: "Petrol", description: "Simple and popular petrol Polo. Coil pack failure and cam chain issues are the main concerns." },
    // VW Passat
    { model_id: find(models,"passat").id, name: "B7 2.0 TDI 140bhp", slug: "passat-b7-20-tdi", engine: "2.0 TDI 140bhp CR", year_start: 2010, year_end: 2014, body_type: "Saloon", transmission: "Manual", fuel_type: "Diesel", description: "A fleet favourite. DSG issues, DPF blockage and EGR failure are the common complaints on high-mileage examples." },
    // VW Tiguan
    { model_id: find(models,"tiguan").id, name: "Mk1 2.0 TDI 140bhp", slug: "tiguan-mk1-20-tdi", engine: "2.0 TDI 140bhp", year_start: 2007, year_end: 2016, body_type: "SUV", transmission: "Manual", fuel_type: "Diesel", description: "VAG's first big crossover. Shares Golf Mk6 underpinnings — DPF and EGR issues transfer across." },
    // BMW 5 Series
    { model_id: find(models,"5-series").id, name: "E60 520d N47 2.0d 177bhp", slug: "e60-520d-n47", engine: "N47 2.0d 177bhp", year_start: 2007, year_end: 2010, body_type: "Saloon", transmission: "Manual", fuel_type: "Diesel", description: "The E60 520d carries the same rear-mounted N47 timing chain as the 3 Series. Chain failure is catastrophic and expensive." },
  ];
  const variants = await upsert("variants", variantRows, "model_id,slug");
  console.log(`Variants: ${variants.length}`);

  const vid = slug => find(variants, slug).id;

  // ── Faults ────────────────────────────────────────────────────────────────
  const faultRows = [

    // ── Ford Transit Custom 2.0 TDCi ──────────────────────────────────────
    { variant_id: vid("transit-custom-20-tdci"), title: "DPF Blockage from Idling and Short Trips", slug: "transit-custom-dpf-blockage", summary: "Fleet Transit Customs spend long periods idling at low speed — the worst possible operating profile for a DPF. Blockage is the number one reported fault across UK fleets.", symptoms: "- DPF warning light\n- Power reduction\n- Black smoke\n- Engine oil rising above max (failed regens)\n- P2452/P2453 codes", cause: "Van use involves frequent idling, slow speeds and short trips. The DPF cannot regenerate below 550°C exhaust temperature. Failed regens pump diesel into the engine oil.", fix: "1. Check oil immediately — change if smells of diesel or above max\n2. Force regen via Forscan or dealer tool\n3. Professional DPF clean: £200-350\n4. Policy: van must do one 30-min motorway run per week", severity: "moderate", mileage_start: 30000, mileage_end: 80000, repair_cost_low: 200, repair_cost_high: 1000, diy_difficulty: "moderate", affected_years: "2013-2021", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("transit-custom-20-tdci"), title: "EGR Valve and Cooler Failure", slug: "transit-custom-egr-failure", summary: "EGR failure on the Transit Custom 2.0 TDCi is extremely common in fleet use. The valve carbons up rapidly in stop-start environments.", symptoms: "- EML and power loss\n- Rough idle\n- Black smoke\n- P0400/P0401 codes", cause: "Stop-start urban van use causes rapid carbon accumulation in the EGR valve. The cooler can also fail, introducing coolant into the intake.", fix: "1. Clean or replace EGR valve\n2. Inspect EGR cooler for internal leaks\n3. Replace together if high mileage\n4. Cost: £300-700 fitted", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 300, repair_cost_high: 700, diy_difficulty: "moderate", affected_years: "2013-2021", obd_codes: ["P0400","P0401"], published: true },

    { variant_id: vid("transit-custom-20-tdci"), title: "Turbocharger Variable Vane Sticking", slug: "transit-custom-turbo-vane", summary: "The VNT turbocharger on the 2.0 TDCi Transit Custom develops sticky variable vanes from carbon build-up, causing power loss and limp mode.", symptoms: "- Sluggish acceleration above 2,000 RPM\n- Limp mode activation\n- P0299 underboost or P0234 overboost\n- Smoke under load", cause: "Variable vane turbochargers use movable vanes to control boost. Carbon and soot from urban use causes the vanes to stick, preventing proper boost control.", fix: "1. Remove turbo and clean vanes with carb cleaner and fine brush\n2. Actuate vanes manually to check for free movement\n3. Replacement if vanes are corroded: remanufactured unit £400-700\n4. Fitted: £600-1,000", severity: "severe", mileage_start: 60000, mileage_end: 130000, repair_cost_low: 200, repair_cost_high: 1000, diy_difficulty: "hard", affected_years: "2013-2021", obd_codes: ["P0299","P0234"], published: true },

    { variant_id: vid("transit-custom-20-tdci"), title: "Dual Mass Flywheel Failure", slug: "transit-custom-dmf-failure", summary: "The Transit Custom carries loads and covers high mileages — both conditions that accelerate DMF wear. A shuddering, rattling van at idle is the typical presentation.", symptoms: "- Clutch judder pulling away under load\n- Rattle from bellhousing at idle\n- Vibration through gear lever\n- Clunking gear changes", cause: "Van use with heavy loads and frequent clutch engagement wears the DMF spring dampers faster than typical car use.", fix: "1. Replace DMF and clutch together — LuK or Sachs heavy-duty kit\n2. Consider solid flywheel conversion for long-term van use\n3. Labour: 5 hours. Total: £800-1,300", severity: "moderate", mileage_start: 80000, mileage_end: 160000, repair_cost_low: 800, repair_cost_high: 1300, diy_difficulty: "professional_only", affected_years: "2013-2021", obd_codes: [], published: true },

    { variant_id: vid("transit-custom-20-tdci"), title: "AdBlue System Fault and NOx Sensor Failure", slug: "transit-custom-adblue-fault", summary: "Post-2016 Euro 6 Transit Customs use AdBlue SCR systems that develop NOx sensor faults, AdBlue pump failures and frozen lines in cold weather.", symptoms: "- AdBlue warning light\n- 'Refill AdBlue' message\n- Countdown to engine start refusal\n- P20EE or P204F fault codes", cause: "NOx sensors are single-use components with a finite lifespan. The AdBlue pump and injector also wear. In cold UK winters, AdBlue tanks can freeze below -11°C.", fix: "1. Refill AdBlue if level is low — 10L typically required\n2. NOx sensor replacement: £150-300 fitted\n3. AdBlue pump failure: £400-700\n4. Clear codes after repair — system reset required", severity: "moderate", mileage_start: 40000, mileage_end: 100000, repair_cost_low: 150, repair_cost_high: 700, diy_difficulty: "moderate", affected_years: "2016-2021", obd_codes: ["P20EE","P204F"], published: true },

    { variant_id: vid("transit-custom-20-tdci"), title: "Injector Failure and Diesel Contamination of Oil", slug: "transit-custom-injector-failure", summary: "High-mileage Transit Customs suffer injector wear, causing diesel to contaminate the engine oil. This is a serious secondary failure that must be caught early.", symptoms: "- Oil level rising above max\n- Diesel smell on dipstick\n- Rough idle and misfire\n- Hard cold starting\n- P0201-P0204 codes", cause: "Worn common rail injectors allow fuel to dribble into the cylinder. During failed DPF regens, diesel also enters the combustion chamber late, washing past piston rings into the oil.", fix: "1. Check oil dipstick — if smells of diesel, change oil immediately before driving\n2. Contribution test to identify failing injector\n3. Ultrasonic clean and test before replacing\n4. New injectors must be coded to ECU\n5. Cost: £250-500 per injector fitted", severity: "severe", mileage_start: 100000, mileage_end: 200000, repair_cost_low: 300, repair_cost_high: 1000, diy_difficulty: "professional_only", affected_years: "2013-2021", obd_codes: ["P0201","P0202","P0087"], published: true },

    // ── Ford Kuga Mk2 2.0 TDCi ────────────────────────────────────────────
    { variant_id: vid("kuga-mk2-20-tdci"), title: "DPF Blockage", slug: "kuga-mk2-dpf-blockage", summary: "The Kuga Mk2 2.0 TDCi is used heavily for school runs and urban duties — prime DPF-blocking territory. It is one of the most commonly reported Kuga faults.", symptoms: "- DPF warning light\n- Power loss and limp mode\n- Oil level rising (diesel contamination)\n- Black smoke\n- P2452/P2453 codes", cause: "Short journeys prevent regeneration. The Kuga's weight means the engine works harder but exhaust temperatures in traffic remain insufficient for passive regen.", fix: "1. Check oil for diesel contamination first\n2. Forced regen via OBD (Forscan)\n3. Professional DPF clean: £200-350\n4. Replacement if damaged: £600-1,200", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 200, repair_cost_high: 1200, diy_difficulty: "moderate", affected_years: "2012-2019", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("kuga-mk2-20-tdci"), title: "EGR Cooler Failure and Coolant Loss", slug: "kuga-mk2-egr-cooler", summary: "EGR cooler failure on the Kuga Mk2 causes coolant to enter the intake. Left unchecked this results in rough running, white smoke and potential engine damage.", symptoms: "- Coolant level dropping\n- White smoke with sweet smell\n- Rough running\n- P0401 EGR fault\n- Steam from engine bay", cause: "The EGR cooler corrodes internally. Coolant leaks into the intake manifold — initially causing rough running, worsening to potential hydro-lock if ignored.", fix: "1. Replace EGR cooler — Valeo or Pierburg OEM unit\n2. Flush intake manifold before restarting\n3. Replace EGR valve at same time\n4. Total: £500-800", severity: "severe", mileage_start: 60000, mileage_end: 130000, repair_cost_low: 500, repair_cost_high: 800, diy_difficulty: "hard", affected_years: "2012-2019", obd_codes: ["P0401","P0128"], published: true },

    { variant_id: vid("kuga-mk2-20-tdci"), title: "Timing Chain Failure", slug: "kuga-mk2-timing-chain", summary: "The 2.0 TDCi Kuga uses the same engine family as the Focus Mk3. Timing chain stretch and tensioner failure at high mileage is a known issue.", symptoms: "- Rattling on cold start from engine front\n- EML with P0016/P0017\n- Rough running\n- Metallic noise under acceleration", cause: "Chain tensioner and guides wear over time. High mileage with infrequent oil changes accelerates the issue.", fix: "1. Full timing chain kit replacement\n2. Fresh 5W-30 synthetic oil on reassembly\n3. Cost: £700-1,300 fitted", severity: "critical", mileage_start: 80000, mileage_end: 150000, repair_cost_low: 700, repair_cost_high: 1300, diy_difficulty: "hard", affected_years: "2012-2019", obd_codes: ["P0016","P0017"], published: true },

    { variant_id: vid("kuga-mk2-20-tdci"), title: "Dual Mass Flywheel Failure", slug: "kuga-mk2-dmf-failure", summary: "The Kuga's weight and diesel torque accelerate DMF wear. Juddering clutch engagement is the first symptom, followed by a characteristic rattle at idle.", symptoms: "- Clutch judder when pulling away\n- Rattle at idle from bellhousing\n- Vibration through gear lever\n- Clunking on changes", cause: "The DMF spring dampers cannot cope indefinitely with the combination of diesel torque pulses and the Kuga's kerb weight.", fix: "1. Replace DMF and clutch together\n2. LuK or Sachs kit recommended\n3. Labour: 5-6 hours. Total: £750-1,200", severity: "moderate", mileage_start: 80000, mileage_end: 150000, repair_cost_low: 750, repair_cost_high: 1200, diy_difficulty: "professional_only", affected_years: "2012-2019", obd_codes: [], published: true },

    { variant_id: vid("kuga-mk2-20-tdci"), title: "Turbocharger Failure", slug: "kuga-mk2-turbo-failure", summary: "Turbo failure on the Kuga Mk2 follows the same pattern as other 2.0 TDCi Ford products — oil sludge in the feed pipe starves the bearings.", symptoms: "- Whining from engine bay\n- Loss of power and boost\n- Blue smoke on acceleration\n- P0299 underboost code", cause: "Sludged oil feed pipe blocks lubrication to turbo bearings. Infrequent oil changes on a diesel SUV are the primary cause.", fix: "1. Check oil feed pipe before replacing turbo\n2. Remanufactured turbo: £400-700\n3. Flush oil system on installation\n4. Fitted: £600-1,100", severity: "severe", mileage_start: 100000, mileage_end: 180000, repair_cost_low: 600, repair_cost_high: 1100, diy_difficulty: "hard", affected_years: "2012-2019", obd_codes: ["P0299"], published: true },

    // ── Ford Mondeo Mk4 2.0 TDCi ──────────────────────────────────────────
    { variant_id: vid("mondeo-mk4-20-tdci"), title: "Dual Mass Flywheel Failure", slug: "mondeo-mk4-dmf-failure", summary: "The Mondeo Mk4 2.0 TDCi is a high-mileage rep car that almost inevitably needs its DMF replaced. It is one of the most consistent known faults across all Mondeo diesel ownership.", symptoms: "- Juddering when pulling away\n- Rattling at idle from gearbox area\n- Gear lever vibration at idle\n- Clunking on gear changes", cause: "High mileage combined with motorway use and diesel torque pulses wears the DMF spring dampers. Most examples need DMF replacement by 120,000 miles.", fix: "1. Replace DMF and clutch as a pair\n2. LuK or Sachs kits recommended\n3. Solid flywheel conversion is a cost-effective option\n4. Labour: 5 hours. Total: £750-1,100", severity: "moderate", mileage_start: 90000, mileage_end: 170000, repair_cost_low: 750, repair_cost_high: 1100, diy_difficulty: "professional_only", affected_years: "2007-2014", obd_codes: [], published: true },

    { variant_id: vid("mondeo-mk4-20-tdci"), title: "DPF Blockage", slug: "mondeo-mk4-dpf-blockage", summary: "DPF blockage affects the Mondeo Mk4 TDCi when used as a local runabout rather than the long-distance motorway car it was designed for. High mileage examples with documented DPF service history are preferable.", symptoms: "- DPF warning light\n- Power restriction\n- Oil above max (diesel dilution)\n- P2452/P2453 codes", cause: "Short local trips prevent regeneration. The Mondeo's larger 2.0-litre diesel produces sufficient exhaust heat at motorway speed but insufficient in town.", fix: "1. Check oil for diesel contamination\n2. Force regen or professional DPF clean\n3. Replacement: £600-1,200", severity: "moderate", mileage_start: 50000, mileage_end: 100000, repair_cost_low: 200, repair_cost_high: 1200, diy_difficulty: "moderate", affected_years: "2007-2014", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("mondeo-mk4-20-tdci"), title: "EGR Valve Failure", slug: "mondeo-mk4-egr-failure", summary: "EGR failure on the Mondeo Mk4 TDCi causes power loss and rough running. Carbon build-up on the valve is the primary cause, accelerated by urban use.", symptoms: "- EML and power loss\n- Rough idle\n- Increased fuel consumption\n- P0400/P0401 codes", cause: "Carbon from recirculated exhaust gas coats the EGR valve and intake passages. The Mondeo's larger displacement means more soot volume through the EGR system.", fix: "1. Remove and clean EGR valve\n2. Clean intake manifold\n3. Replace if worn beyond cleaning\n4. Cost: £200-450 fitted", severity: "moderate", mileage_start: 60000, mileage_end: 120000, repair_cost_low: 200, repair_cost_high: 450, diy_difficulty: "moderate", affected_years: "2007-2014", obd_codes: ["P0400","P0401"], published: true },

    { variant_id: vid("mondeo-mk4-20-tdci"), title: "Power Steering Rack Failure", slug: "mondeo-mk4-steering-rack", summary: "The Mondeo Mk4 uses an electric power steering rack that can develop faults, leaving the car with very heavy or completely absent power steering assistance.", symptoms: "- Heavy steering warning light\n- Loss of power steering assistance\n- Intermittent steering heaviness\n- Clunking from steering rack\n- U3000 or C1288 fault codes", cause: "The EPS control module and motor develop faults with age. High-mileage examples (130k+) are more susceptible. The rack position sensor can also fail.", fix: "1. Check for fault codes before condemning the rack\n2. Remanufactured rack available on exchange: £200-400\n3. Programming required after replacement\n4. Fitted: £400-700", severity: "moderate", mileage_start: 100000, mileage_end: 180000, repair_cost_low: 400, repair_cost_high: 700, diy_difficulty: "professional_only", affected_years: "2007-2014", obd_codes: ["U3000","C1288"], published: true },

    { variant_id: vid("mondeo-mk4-20-tdci"), title: "Turbocharger Failure", slug: "mondeo-mk4-turbo-failure", summary: "Turbocharger failure on the high-mileage Mondeo Mk4 TDCi is common after 120,000 miles. Oil sludge and worn bearings are the usual causes.", symptoms: "- Loud whining from turbo\n- Loss of power\n- Blue smoke\n- P0299 underboost", cause: "Oil sludge blocks the turbo feed pipe. Combined with general bearing wear at high mileage, turbo failure follows.", fix: "1. Check feed pipe first\n2. Remanufactured turbo: £350-600\n3. Flush oil system on install\n4. Fitted: £550-950", severity: "severe", mileage_start: 120000, mileage_end: 200000, repair_cost_low: 550, repair_cost_high: 950, diy_difficulty: "hard", affected_years: "2007-2014", obd_codes: ["P0299"], published: true },

    // ── VW Polo Mk5 1.2 TDI ───────────────────────────────────────────────
    { variant_id: vid("polo-mk5-12-tdi"), title: "Timing Belt Failure", slug: "polo-mk5-tdi-timing-belt", summary: "The 1.2 TDI Polo has a timing belt that must be replaced at 60,000 miles or 4 years. Many owners are unaware of this interval — belt failure destroys the engine on this interference unit.", symptoms: "- No warning before failure\n- Engine stops suddenly\n- Engine will not restart\n- Bent valves and damaged pistons on failure", cause: "The rubber belt degrades with age and mileage. The strict 60k/4yr interval is non-negotiable. Many second-hand Polos have unknown belt history.", fix: "1. Replace belt, tensioner, idler and water pump as a kit\n2. If belt history unknown: replace immediately\n3. Gates or Dayco kit only\n4. Cost: £280-500 fitted", severity: "critical", mileage_start: 1, mileage_end: 60000, repair_cost_low: 280, repair_cost_high: 500, diy_difficulty: "hard", affected_years: "2009-2014", obd_codes: [], published: true },

    { variant_id: vid("polo-mk5-12-tdi"), title: "EGR Valve Failure", slug: "polo-mk5-tdi-egr-failure", summary: "EGR failure on the 1.2 TDI Polo is a regular occurrence. The small-displacement engine's EGR system clogs readily in urban use.", symptoms: "- EML and power loss\n- Rough idle\n- Black smoke\n- P0400/P0401 codes", cause: "Carbon deposits from exhaust gas recirculation coat the EGR valve and restrict flow. City-only use is the primary cause.", fix: "1. Remove and clean EGR valve\n2. Clean intake passages\n3. Replace if seized\n4. Cost: £150-350 fitted", severity: "moderate", mileage_start: 40000, mileage_end: 80000, repair_cost_low: 150, repair_cost_high: 350, diy_difficulty: "moderate", affected_years: "2009-2014", obd_codes: ["P0400","P0401"], published: true },

    { variant_id: vid("polo-mk5-12-tdi"), title: "DPF Blockage", slug: "polo-mk5-tdi-dpf-blockage", summary: "The smallest diesel engine VW sell with a DPF is also the most prone to blocking it — the 1.2 TDI Polo simply cannot generate enough heat from urban driving for reliable regeneration.", symptoms: "- DPF warning light\n- Power reduction\n- P2452/P2453 codes\n- Black smoke", cause: "The 1.2-litre engine has very low exhaust mass flow. Short trips mean the DPF never gets hot enough to self-clean.", fix: "1. 30-min motorway run at 2,500+ RPM\n2. Force regen via VCDS or OBD tool\n3. Professional clean: £150-300\n4. Consider avoiding diesel Polo for city use entirely", severity: "moderate", mileage_start: 30000, mileage_end: 70000, repair_cost_low: 150, repair_cost_high: 800, diy_difficulty: "moderate", affected_years: "2009-2014", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("polo-mk5-12-tdi"), title: "Injector Failure", slug: "polo-mk5-tdi-injector-failure", summary: "Injector wear on the 1.2 TDI causes rough running and smoke. The three-cylinder engine runs with high injection pressures that accelerate injector wear.", symptoms: "- Rough idle and misfire\n- White smoke on start\n- Hard starting\n- P0201-P0203 codes", cause: "Three-cylinder engines produce high torque pulses that stress injectors. Worn injectors allow unmetered fuel into the cylinder.", fix: "1. Contribution test to identify failing cylinder\n2. Clean and test before replacing\n3. New injectors need ECU coding\n4. Cost: £200-400 per injector fitted", severity: "moderate", mileage_start: 80000, mileage_end: 150000, repair_cost_low: 250, repair_cost_high: 600, diy_difficulty: "professional_only", affected_years: "2009-2014", obd_codes: ["P0201","P0202","P0203"], published: true },

    // ── VW Polo Mk5 1.4 ───────────────────────────────────────────────────
    { variant_id: vid("polo-mk5-14-85"), title: "Timing Chain Rattle on Cold Start", slug: "polo-mk5-14-timing-chain", summary: "The 1.4 petrol Polo uses a timing chain, but the tensioner weakens with age causing a cold-start rattle. Left unchecked, chain stretch causes valve timing issues.", symptoms: "- Rattle on cold start, clears as oil pressure builds\n- P0016/P0017 on scan\n- Engine roughness when cold", cause: "The hydraulic tensioner relies on oil pressure. On cold starts there is a brief moment of low pressure. A worn chain amplifies this into a rattle.", fix: "1. Short interval oil changes (6,000 miles max, 5W-30 synthetic)\n2. Full chain kit replacement if rattle persists\n3. Cost: £400-700 fitted", severity: "moderate", mileage_start: 70000, mileage_end: 140000, repair_cost_low: 400, repair_cost_high: 700, diy_difficulty: "hard", affected_years: "2009-2017", obd_codes: ["P0016","P0017"], published: true },

    { variant_id: vid("polo-mk5-14-85"), title: "Coil Pack and Ignition Failure", slug: "polo-mk5-14-coil-pack", summary: "Coil pack failure on the 1.4 Polo causes misfires and rough running. Individual coil packs are inexpensive but the fault can be mistaken for more serious engine problems.", symptoms: "- Rough idle and misfires\n- EML flashing (active misfire)\n- Loss of power on one cylinder\n- P030X misfire codes", cause: "Individual coil packs for each cylinder deteriorate with heat and vibration. Aftermarket packs are poor quality — genuine or OEM-spec Bosch/Bremi units are essential.", fix: "1. Read codes — P0301-P0304 identifies cylinder\n2. Swap the coil from the faulty cylinder to another — if misfire moves, coil is confirmed\n3. Replace faulty coil (£15-30 each, genuine VW or Bosch)\n4. Replace all four if over 80,000 miles — prevent future failures", severity: "moderate", mileage_start: 50000, mileage_end: 120000, repair_cost_low: 50, repair_cost_high: 200, diy_difficulty: "easy", affected_years: "2009-2017", obd_codes: ["P0301","P0302","P0303","P0304"], published: true },

    { variant_id: vid("polo-mk5-14-85"), title: "Throttle Body Failure", slug: "polo-mk5-14-throttle-body", summary: "Throttle body contamination and electronic throttle actuator failure cause hunting idle and poor response on the 1.4 Polo. A common and inexpensive fix if caught early.", symptoms: "- Hunting or fluctuating idle\n- Hesitation under light throttle\n- Limp mode in severe cases\n- P0506/P0507 or P0122 codes", cause: "Oil vapour from the PCV system coats the throttle blade over time. The electronic throttle actuator motor can also develop faults independent of contamination.", fix: "1. Clean throttle body with carb cleaner — cheap first step\n2. Perform throttle body adaptation via VCDS or OBD after cleaning\n3. Replacement throttle body if motor has failed: £80-150\n4. Fitted: £150-300", severity: "minor", mileage_start: 50000, mileage_end: 120000, repair_cost_low: 50, repair_cost_high: 300, diy_difficulty: "easy", affected_years: "2009-2017", obd_codes: ["P0506","P0507","P0122"], published: true },

    // ── VW Passat B7 2.0 TDI ─────────────────────────────────────────────
    { variant_id: vid("passat-b7-20-tdi"), title: "DSG 7-Speed DQ200 Dry Clutch Shudder", slug: "passat-b7-dsg-shudder", summary: "The DSG 7-speed DQ200 dry clutch gearbox in the Passat B7 has a well-documented shudder issue from a standing start. VW issued multiple software and mechatronic updates.", symptoms: "- Shudder or vibration when pulling away from 0-10 mph\n- Hesitation on DSG engagement\n- Jerky low-speed driving\n- Clunking on gear changes", cause: "The dry clutch DQ200 DSG operates differently to the wet-clutch DQ250. The dry clutches require precise software control at low speed — early software versions caused hunting and shudder.", fix: "1. Software update via VCDS or dealer (often free under goodwill)\n2. Mechatronic unit replacement if clutch is worn (£800-1,500)\n3. Full dual-clutch replacement if worn: £1,500-2,500\n4. Check DSG service history — fluid must be changed every 40,000 miles", severity: "moderate", mileage_start: 30000, mileage_end: 100000, repair_cost_low: 100, repair_cost_high: 2500, diy_difficulty: "professional_only", affected_years: "2010-2014", obd_codes: ["P17BF","P189A"], published: true },

    { variant_id: vid("passat-b7-20-tdi"), title: "EGR Cooler Failure", slug: "passat-b7-egr-cooler", summary: "EGR cooler failure on the Passat B7 2.0 TDI causes coolant loss and white smoke. The internal corrosion of the cooler allows coolant into the intake manifold.", symptoms: "- Coolant loss without visible leak\n- White smoke with sweet smell\n- Rough running after extended idling\n- P0401 EGR fault", cause: "Coolant passages inside the EGR cooler corrode with age. Coolant leaks into the recirculated exhaust gas path and enters the intake.", fix: "1. Replace EGR cooler and valve together\n2. Flush intake manifold\n3. OEM Pierburg or Valeo unit\n4. Cost: £500-900 fitted", severity: "severe", mileage_start: 70000, mileage_end: 140000, repair_cost_low: 500, repair_cost_high: 900, diy_difficulty: "hard", affected_years: "2010-2014", obd_codes: ["P0401","P0128"], published: true },

    { variant_id: vid("passat-b7-20-tdi"), title: "DPF Blockage", slug: "passat-b7-dpf-blockage", summary: "The Passat B7 TDI is often used as a company car for short local journeys — not the motorway machine it was designed to be. DPF blockage is the inevitable result.", symptoms: "- DPF warning light\n- Power loss\n- Oil level rising\n- P2452/P2453 codes", cause: "Short trips prevent DPF regeneration. Failed regens contaminate the engine oil with diesel.", fix: "1. Check oil for diesel dilution first\n2. Force regen via VCDS\n3. Professional clean: £200-350\n4. Replacement: £600-1,200", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 200, repair_cost_high: 1200, diy_difficulty: "moderate", affected_years: "2010-2014", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("passat-b7-20-tdi"), title: "Timing Belt Failure (CFFB/CEGA Engines)", slug: "passat-b7-timing-belt", summary: "Unlike the older PD-engine Passats, the B7 common rail 2.0 TDI uses a timing belt. The belt interval is 140,000 miles but many specialists recommend 100,000 miles given the cost of engine damage.", symptoms: "- No warning before failure\n- Engine stops when belt snaps\n- Engine does not restart\n- Catastrophic engine damage", cause: "Rubber timing belt deterioration with age and heat. The B7's 140k interval is generous — belt condition should be checked at every service.", fix: "1. Replace belt, tensioner, idler and water pump as a complete kit\n2. Recommended at 100k miles regardless of official interval\n3. Gates or Dayco belt kit only\n4. Cost: £400-700 fitted", severity: "critical", mileage_start: 100000, mileage_end: 140000, repair_cost_low: 400, repair_cost_high: 700, diy_difficulty: "hard", affected_years: "2010-2014", obd_codes: [], published: true },

    { variant_id: vid("passat-b7-20-tdi"), title: "Injector Failure", slug: "passat-b7-injector-failure", summary: "High-mileage Passat B7 TDIs suffer injector wear. The common rail system operates at extreme pressure and injector precision degrades with use.", symptoms: "- Rough idle and misfire\n- Hard cold starting\n- White smoke on startup\n- Oil level rising (diesel dilution)\n- P0201-P0204 codes", cause: "Common rail injectors wear at the control valve and needle seats over hundreds of thousands of injections. Contaminated fuel or extended filter service intervals accelerate this.", fix: "1. Contribution test identifies worst cylinder\n2. Ultrasonic clean and test before replacing\n3. New injectors coded to ECU by diesel specialist\n4. Cost: £250-500 per injector fitted", severity: "severe", mileage_start: 100000, mileage_end: 200000, repair_cost_low: 300, repair_cost_high: 1000, diy_difficulty: "professional_only", affected_years: "2010-2014", obd_codes: ["P0201","P0202","P0263"], published: true },

    // ── VW Tiguan Mk1 2.0 TDI ────────────────────────────────────────────
    { variant_id: vid("tiguan-mk1-20-tdi"), title: "DPF Blockage", slug: "tiguan-mk1-dpf-blockage", summary: "The Tiguan Mk1 TDI is a family SUV often used on school runs and urban trips. DPF blockage is the single most common fault reported by UK Tiguan owners.", symptoms: "- DPF warning light\n- Power restriction and limp mode\n- Oil level rising above max\n- P2452/P2453 codes", cause: "The Tiguan's weight means the engine works harder in traffic but exhaust temperatures remain insufficient for passive regen. Short trips compound the problem.", fix: "1. Check oil for diesel dilution immediately\n2. Force regen via VCDS\n3. Professional DPF clean: £200-350\n4. Replacement: £600-1,200", severity: "moderate", mileage_start: 40000, mileage_end: 90000, repair_cost_low: 200, repair_cost_high: 1200, diy_difficulty: "moderate", affected_years: "2007-2016", obd_codes: ["P2452","P2453"], published: true },

    { variant_id: vid("tiguan-mk1-20-tdi"), title: "EGR Valve and Cooler Failure", slug: "tiguan-mk1-egr-failure", summary: "EGR failure on the Tiguan Mk1 2.0 TDI causes power loss and in more serious cases, coolant loss from the EGR cooler. Both components often need addressing together.", symptoms: "- EML and power restriction\n- Rough idle\n- Coolant loss (cooler failure)\n- P0401 or P0402 codes", cause: "Carbon deposits block the EGR valve; the EGR cooler corrodes internally and leaks coolant. Urban use accelerates both failures.", fix: "1. Replace EGR valve and cooler together\n2. Flush intake manifold\n3. OEM quality parts only\n4. Cost: £500-850 fitted", severity: "severe", mileage_start: 60000, mileage_end: 130000, repair_cost_low: 500, repair_cost_high: 850, diy_difficulty: "hard", affected_years: "2007-2016", obd_codes: ["P0401","P0402"], published: true },

    { variant_id: vid("tiguan-mk1-20-tdi"), title: "Haldex 4MOTION Rear Differential Failure", slug: "tiguan-mk1-haldex-failure", summary: "4MOTION Tiguans use a Haldex rear differential coupling. Failure of the Haldex pump or fluid contamination causes the rear wheels to lose drive — effectively turning it into a front-wheel drive.", symptoms: "- Reduced traction on slippery surfaces\n- Fault light for 4WD system\n- Rear wheels not driving\n- 4WD system warning on dashboard", cause: "The Haldex clutch pack and pump require oil changes every 40,000 miles. Neglected fluid breaks down and causes pump and clutch wear. The filter also becomes blocked.", fix: "1. Haldex oil and filter service: £100-200 (often neglected by previous owners)\n2. Haldex pump replacement if worn: £300-600\n3. Full Haldex unit replacement: £800-1,500\n4. Always service Haldex on purchase if history unknown", severity: "severe", mileage_start: 60000, mileage_end: 140000, repair_cost_low: 100, repair_cost_high: 1500, diy_difficulty: "moderate", affected_years: "2007-2016", obd_codes: ["P0859"], published: true },

    { variant_id: vid("tiguan-mk1-20-tdi"), title: "Turbocharger Failure", slug: "tiguan-mk1-turbo-failure", summary: "Turbo failure on the Tiguan 2.0 TDI follows the same pattern as Golf and Passat — oil sludge in the feed pipe leads to bearing failure. The SUV's extra weight increases turbo load.", symptoms: "- Whining from engine bay\n- Loss of boost and power\n- Blue smoke\n- P0299 underboost", cause: "Oil sludge blocks the turbo oil feed. The Tiguan's extra mass requires the turbo to work harder at low speed, increasing heat and wear.", fix: "1. Check oil feed pipe\n2. Remanufactured turbo: £400-700\n3. Flush oil on installation\n4. Fitted: £650-1,100", severity: "severe", mileage_start: 90000, mileage_end: 170000, repair_cost_low: 650, repair_cost_high: 1100, diy_difficulty: "hard", affected_years: "2007-2016", obd_codes: ["P0299"], published: true },

    // ── BMW E60 520d N47 ──────────────────────────────────────────────────
    { variant_id: vid("e60-520d-n47"), title: "N47 Rear Timing Chain Failure", slug: "bmw-e60-n47-timing-chain", summary: "The E60 5 Series with the N47 diesel engine carries the same catastrophic rear-mounted timing chain risk as the E90 3 Series. Engine removal is required for repair — making this one of the most expensive known faults in the BMW range.", symptoms: "- Rattling from rear of engine on cold start\n- Noise fades as oil pressure builds but returns when cold\n- P0016/P0017 timing codes\n- In failure: sudden engine cut-out, catastrophic damage", cause: "BMW placed the N47 timing chain at the rear of the engine. The chain, guides and tensioner all wear — but because access requires engine removal, the job is far more expensive than a front-mounted chain.", fix: "1. Listen for the rattle — it comes from behind the engine, not the front\n2. Stop driving immediately if rattle is heard\n3. Engine removal required for chain replacement\n4. Cost: £2,500-4,000 at a BMW specialist\n5. Always ask: 'has the timing chain been replaced?' before buying any N47 E60", severity: "critical", mileage_start: 80000, mileage_end: 160000, repair_cost_low: 2500, repair_cost_high: 4000, diy_difficulty: "professional_only", affected_years: "2007-2010", obd_codes: ["P0016","P0017"], published: true },

    { variant_id: vid("e60-520d-n47"), title: "Swirl Flap Failure and Engine Ingestion", slug: "bmw-e60-n47-swirl-flap", summary: "The N47 in the E60 5 Series shares the swirl flap failure risk of all N47-engined BMWs. The flap breaks off the corroded actuator rod and is ingested into the engine.", symptoms: "- Sudden loss of power\n- Loud metallic bang\n- P2004/P2008 intake manifold codes\n- Engine misfires after the event\n- Metal debris in intake", cause: "The alloy swirl flap actuator rods corrode in UK conditions. When the rod snaps, the free flap is drawn into the engine. Piston damage ranges from dents to total destruction.", fix: "1. Preventative: remove swirl flaps and fit blanking plates (£30-50 parts, 2-3 hours)\n2. Post-failure: compression test all cylinders immediately\n3. Borescope inspection through spark plug holes\n4. Engine rebuild if piston damage confirmed: £3,000-6,000", severity: "critical", mileage_start: 60000, mileage_end: 130000, repair_cost_low: 30, repair_cost_high: 6000, diy_difficulty: "moderate", affected_years: "2007-2010", obd_codes: ["P2004","P2006","P2008"], published: true },

    { variant_id: vid("e60-520d-n47"), title: "EGR Failure and Coolant Loss", slug: "bmw-e60-n47-egr-failure", summary: "EGR cooler failure on the E60 520d N47 causes internal coolant leaks into the intake manifold. Combined with EGR valve carbonising, both components typically need replacing together.", symptoms: "- Coolant level dropping\n- White smoke with sweet smell\n- Rough running after idling\n- P0401 EGR code", cause: "Internal EGR cooler corrosion allows coolant to enter the intake. The EGR valve simultaneously builds up carbon deposits from the recirculated exhaust.", fix: "1. Replace EGR cooler and valve together\n2. Flush intake before restarting\n3. OEM BMW parts recommended\n4. Cost: £700-1,200 at BMW specialist", severity: "moderate", mileage_start: 70000, mileage_end: 140000, repair_cost_low: 700, repair_cost_high: 1200, diy_difficulty: "hard", affected_years: "2007-2010", obd_codes: ["P0401","P0128"], published: true },

    { variant_id: vid("e60-520d-n47"), title: "Turbocharger Failure", slug: "bmw-e60-n47-turbo-failure", summary: "Turbo failure on the E60 520d N47 is common from 100,000 miles. The 5 Series tends to be driven harder than the 3 Series, increasing turbo stress.", symptoms: "- Loud whining from turbo\n- Loss of boost and performance\n- Blue smoke on acceleration\n- P0299 underboost", cause: "Oil sludge or low oil level starves the turbo bearings. High-speed motorway use followed by switching off without a cool-down period (heat soak) also causes bearing damage.", fix: "1. Check oil feed pipe for blockage\n2. Shaft play test — radial play confirms bearing failure\n3. Remanufactured unit: £500-900\n4. Fitted at BMW specialist: £800-1,400", severity: "severe", mileage_start: 100000, mileage_end: 180000, repair_cost_low: 800, repair_cost_high: 1400, diy_difficulty: "hard", affected_years: "2007-2010", obd_codes: ["P0299"], published: true },

    { variant_id: vid("e60-520d-n47"), title: "Cooling System Thermostat Housing Failure", slug: "bmw-e60-n47-thermostat", summary: "The plastic thermostat housing on the N47 is notorious for cracking and causing coolant loss. BMW used plastic for this component in a bid to save weight — it fails prematurely.", symptoms: "- Coolant loss without external leak under engine\n- Overheating warning light\n- Coolant puddle under car after a run\n- Temperature gauge climbing above normal", cause: "The plastic housing is stressed by repeated thermal cycling. Hairline cracks develop at the sealing faces, allowing coolant to leak. Failures become more common from 70,000 miles.", fix: "1. Replace thermostat housing with the updated part (some have been revised)\n2. Replace thermostat at the same time\n3. Bleed cooling system carefully after refill\n4. Cost: £200-400 fitted at BMW specialist", severity: "moderate", mileage_start: 70000, mileage_end: 140000, repair_cost_low: 200, repair_cost_high: 400, diy_difficulty: "moderate", affected_years: "2007-2010", obd_codes: ["P0128","P0217"], published: true },

  ]; // end faultRows

  const insertedFaults = await upsert("faults", faultRows, "slug");
  console.log(`Faults: ${insertedFaults.length}`);

  // Tag links
  const tagMap = {
    "transit-custom-dpf-blockage":      ["dpf"],
    "transit-custom-egr-failure":       ["egr","cooling"],
    "transit-custom-turbo-vane":        ["turbo"],
    "transit-custom-dmf-failure":       ["flywheel","clutch"],
    "transit-custom-adblue-fault":      ["electrics","engine"],
    "transit-custom-injector-failure":  ["injectors"],
    "kuga-mk2-dpf-blockage":            ["dpf"],
    "kuga-mk2-egr-cooler":              ["egr","cooling"],
    "kuga-mk2-timing-chain":            ["timing-chain","engine"],
    "kuga-mk2-dmf-failure":             ["flywheel","clutch"],
    "kuga-mk2-turbo-failure":           ["turbo"],
    "mondeo-mk4-dmf-failure":           ["flywheel","clutch"],
    "mondeo-mk4-dpf-blockage":          ["dpf"],
    "mondeo-mk4-egr-failure":           ["egr"],
    "mondeo-mk4-steering-rack":         ["steering","electrics"],
    "mondeo-mk4-turbo-failure":         ["turbo"],
    "polo-mk5-tdi-timing-belt":         ["timing-belt","engine"],
    "polo-mk5-tdi-egr-failure":         ["egr"],
    "polo-mk5-tdi-dpf-blockage":        ["dpf"],
    "polo-mk5-tdi-injector-failure":    ["injectors"],
    "polo-mk5-14-timing-chain":         ["timing-chain","engine"],
    "polo-mk5-14-coil-pack":            ["electrics","engine"],
    "polo-mk5-14-throttle-body":        ["engine"],
    "passat-b7-dsg-shudder":            ["gearbox"],
    "passat-b7-egr-cooler":             ["egr","cooling"],
    "passat-b7-dpf-blockage":           ["dpf"],
    "passat-b7-timing-belt":            ["timing-belt","engine"],
    "passat-b7-injector-failure":       ["injectors"],
    "tiguan-mk1-dpf-blockage":          ["dpf"],
    "tiguan-mk1-egr-failure":           ["egr","cooling"],
    "tiguan-mk1-haldex-failure":        ["gearbox"],
    "tiguan-mk1-turbo-failure":         ["turbo"],
    "bmw-e60-n47-timing-chain":         ["timing-chain","engine"],
    "bmw-e60-n47-swirl-flap":           ["swirl-flaps","engine"],
    "bmw-e60-n47-egr-failure":          ["egr","cooling"],
    "bmw-e60-n47-turbo-failure":        ["turbo"],
    "bmw-e60-n47-thermostat":           ["cooling"],
  };

  const tagBySlug   = Object.fromEntries(tags.map(t => [t.slug, t.id]));
  const faultBySlug = Object.fromEntries(insertedFaults.map(f => [f.slug, f.id]));
  const ftRows = [];
  for (const [fs, ts] of Object.entries(tagMap)) {
    const fid = faultBySlug[fs]; if (!fid) continue;
    for (const t of ts) { const tid = tagBySlug[t]; if (tid) ftRows.push({ fault_id: fid, tag_id: tid }); }
  }
  await noReturn("fault_tags", ftRows, "fault_id,tag_id");
  console.log(`Tag links: ${ftRows.length}`);

  const { count } = await sb.from("faults").select("*", { count: "exact", head: true }).eq("published", true);
  console.log(`\nTotal published faults: ${count}`);
}

run().catch(e => { console.error("Error:", e.message); process.exit(1); });
